Trying to create a personal 3D stitiching algorithm

In [58]:
import tifffile
import pandas as pd
from skimage.measure import regionprops, regionprops_table
import napari
import numpy as np
import os



def properties_mask(image):

    # Get the properties of every mask in the image
    props = regionprops(image)

    data = []

    # For every mask found, get the label, centeroid, boundingbox, and volume
    for prop in props:
        label = prop.label
        centroid = prop.centroid  # (z, y, x)
        bounding_box = prop.bbox  # (min_z, min_y, min_x, max_z, max_y, max_x)
        volume = prop.area
        
        # Pre-compute coordinate set for fast IOU calculations later
        coords_2d = prop.coords[:, 1:]
        coords_set = set(map(tuple, coords_2d))

        data.append(
            {
                "label": label,
                "z": centroid[0],
                "y": centroid[1],
                "x": centroid[2],
                "bounding_box": bounding_box,
                "volume": volume,
                "coords_set": coords_set,
            }
        )

    # Make a pandas data frame from the data
    df_props = pd.DataFrame(data)

    return df_props


def properties_channel(mask, image, type=None):

    # Get the properties of the mask for the channel you specified (image)
    props_channel = regionprops_table(
        mask, intensity_image=image, properties=["label", "mean_intensity"]
    )

    # Make this into a pandas dataframe and rename some variables to the name of the channel for later merging
    props_channel = pd.DataFrame(props_channel).rename(
        columns={
            "label": "label",
            "mean_intensity": f"raw_{type}",
        }
    )

    return props_channel

def make_unique_mask(mask):
    """Makes a fresh mask from a already stitched mask"""
    unique_mask = []
    number = 1
    for z in range(mask.shape[0]):
        # go over every unique number in the mask and create a new slice with a new unique number 1 higher
        slice = mask[z]
        unique_slice = mask[z].copy()
        for val in range(1, slice.max() + 1):
            unique_slice[slice == val] = number
            number += 1
        unique_mask.append(unique_slice)
    unique_mask = np.stack(unique_mask, axis=0)

    return unique_mask

Dual nuclei image

In [59]:
# generate mask
import os
import sys
sys.path.insert(0, os.path.dirname(os.getcwd()))
import utils

image = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\cropped\Frame-0.tif"
)

nuclei = image[:, 0:1]

nuclei = np.max(image, axis=1)

model = utils.load_model(r"C:\Users\6331823\Local SSD\Train dual nuclei 20x\models\dual_nuclei")

mask = utils.segment(nuclei, model)

tifffile.imwrite(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\Frame-0_segmented.tif",
    mask,
)

KeyboardInterrupt:

In [ ]:
image = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\cropped\Frame-0.tif"
)
crc_image = image[:,0]
wt_image = image[:,1]
mask = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\Frame-0_segmented.tif"
)

print(crc_image.shape, wt_image.shape, mask.shape)

unique_mask = make_unique_mask(mask)

props_mask = properties_mask(unique_mask)
props_wt = properties_channel(unique_mask, wt_image, type="wt")
props_crc = properties_channel(unique_mask, crc_image, type="crc")

# Merge all the dataframes together on the label
df_final = props_mask.merge(props_wt, on="label").merge(props_crc, on="label")

(63, 356, 370) (63, 356, 370) (63, 356, 370)

In [87]:
# using the fake data
import os
import sys

sys.path.insert(0, os.path.dirname(os.getcwd()))
import utils

output_directory = r"C:\Users\6331823\Local SSD\Fake_data"

image = tifffile.imread(os.path.join(output_directory, "realistic_organoid.tif"))

model = utils.load_model(
    r"C:\Users\6331823\Local SSD\Train dual nuclei 20x\models\dual_nuclei"
)

mask = utils.segment(image, model)

tifffile.imwrite(
    os.path.join(output_directory, "realistic_organoid_segmented.tif"),
    mask,
)

Using CUDA for processing.
loaded custom model: dual_nuclei

In [109]:
image = tifffile.imread(
    os.path.join(output_directory, "realistic_organoid.tif"))

image_wt = image_crc = image
# make a fake channel layer at axis 1
mask = tifffile.imread(
    os.path.join(output_directory, "realistic_organoid_segmented.tif")
)
perfect_mask = tifffile.imread(
    os.path.join(output_directory, "perfect_mask.tif")
)

unique_mask = make_unique_mask(mask)

props_mask = properties_mask(unique_mask)
props_wt = properties_channel(unique_mask, image, type="wt")
props_crc = properties_channel(unique_mask, image, type="crc")

# Merge all the dataframes together on the label
df_final = props_mask.merge(props_wt, on="label").merge(props_crc, on="label")

In [ ]:
def get_mask_properties(mask, image1, image2 = None):
    unique_mask = make_unique_mask(mask)

    props_mask = properties_mask(unique_mask)
    props_wt = properties_channel(unique_mask, image1, type="wt")
    if image2 is not None:
        props_crc = properties_channel(unique_mask, image2, type="crc")
        # Merge all the dataframes together on the label
        df_final = props_mask.merge(props_wt, on="label").merge(props_crc, on="label")
    else:
        df_final = props_mask.merge(props_wt, on="label")

    return df_final, unique_mask

def calculate_iou(coords_sets, idx1, idx2):
    """
    Calculate overlap metric for cell matching.
    Returns 1 if the smaller cell is completely contained in the larger cell.
    Otherwise returns intersection over union (standard IOU).
    """
    set1 = coords_sets[idx1]
    set2 = coords_sets[idx2]

    # Check if either set is empty
    len1, len2 = len(set1), len(set2)
    if len2 == 0:
        return 0

    # Calculate intersection (overlapping pixels)
    intersection = len(set1 & set2)

    if intersection == 0:
        return 0  # No overlap = different cells

    # If the smaller cell is completely contained in the larger cell, return 1
    min_len = min(len1, len2)
    if intersection == min_len:
        return 1.0  # One cell completely covers the other

    # Otherwise, use standard IOU
    union = len1 + len2 - intersection
    return intersection / union

def IOU_stitching(data, unique_mask):

    print("Starting IOU-based stitching...")
    df_final = data.copy()
    # Reset index to ensure sequential 0-based indexing
    df_final = df_final.reset_index(drop=True)

    df_final["3d_label"] = -1  # Use -1 to indicate unassigned
    mask_3D = np.zeros_like(unique_mask)
    coords_sets = df_final["coords_set"].to_dict()

    z_groups = {}
    for idx, z_val in df_final["z"].items():
        z_int = int(round(z_val))
        if z_int not in z_groups:
            z_groups[z_int] = []
        z_groups[z_int].append(idx)

    z_array = df_final["z"].values
    x_array = df_final["x"].values
    y_array = df_final["y"].values
    labels_array = np.full(len(df_final), -1, dtype=np.int32)

    def stitch_forward(idx, current_label):
        """Simplified recursive stitching - idx is now both pandas index and array position"""
        current_z = int(round(z_array[idx]))

        # Assign the current label
        labels_array[idx] = current_label

        # Fast lookup: get only indices in the next slice
        next_z = current_z + 1
        if next_z not in z_groups:
            return

        candidates = z_groups[next_z]

        # Filter unassigned candidates
        unassigned_candidates = [c for c in candidates if labels_array[c] == -1]

        if len(unassigned_candidates) == 0:
            return

        # Vectorized distance calculation
        unassigned_array = np.array(unassigned_candidates)
        distances = np.sqrt(
            (x_array[unassigned_array] - x_array[idx]) ** 2
            + (y_array[unassigned_array] - y_array[idx]) ** 2
        )

        # Find the closest candidate
        closest_idx = np.argmin(distances)
        closest_distance = distances[closest_idx]

        # Only proceed if the closest cell is within threshold
        if closest_distance > 10:
            return

        # Get the closest candidate's index
        closest_candidate = unassigned_array[closest_idx]

        # Check IOU with the closest candidate only
        iou = calculate_iou(coords_sets,idx, closest_candidate)
        if iou > 0.3:
            # Recursively stitch this cell forward
            stitch_forward(closest_candidate, current_label)

    unique_label = 0
    for idx in range(len(df_final)):
        if labels_array[idx] == -1:
            unique_label += 1
            stitch_forward(idx, unique_label)

    # Copy results back to dataframe
    df_final["3d_label"] = labels_array

    print(f"Total unique 3D cells found: {unique_label} via IOU stitching")

    # Vectorized mask creation
    mask_3D = np.zeros_like(unique_mask)
    for idx, row in df_final.iterrows():
        z = int(row["z"])
        label_3d = labels_array[idx]
        mask_3D[z][unique_mask[z] == row["label"]] = label_3d

    return df_final, mask_3D


def break_score(values, i):
    # Calculate intensity-based anomalies by getting a score that resembles high-low-high intensity value patterns
    # Calculate ratio between slice i and below i, and i and above i
    values_bottom = max(values[:i])
    values_top = max(values[i + 1 :])
    ratio_1 = values_bottom / values[i]
    ratio_2 = values[i] / values_top

    # divide this again, now high low high gets higher score then other patterns
    ratio_total = ratio_1 / ratio_2
    return ratio_total


def point_line_distance(z_positions, x_positions, y_positions, points=3):
    # Fit line to specified points (int, tuple, or slice)
    if isinstance(points, tuple):
        points = slice(*points)
    elif isinstance(points, int):
        points = slice(None, points)

    z_fit = np.array(z_positions[points])
    x_fit = np.array(x_positions[points])
    y_fit = np.array(y_positions[points])

    # Calculate line parameters
    A = np.vstack([z_fit, np.ones(len(z_fit))]).T
    m_x, c_x = np.linalg.lstsq(A, x_fit, rcond=None)[0]
    m_y, c_y = np.linalg.lstsq(A, y_fit, rcond=None)[0]

    # Create line function: given z, returns (x, y)
    line_function = lambda z: (m_x * z + c_x, m_y * z + c_y)

    # Calculate distances for all points
    distances = []
    for i in range(len(z_positions)):
        z_val = z_positions[i]
        x_line = m_x * z_val + c_x
        y_line = m_y * z_val + c_y
        distance = np.sqrt(
            (x_positions[i] - x_line) ** 2 + (y_positions[i] - y_line) ** 2
        )
        distances.append(distance)
    return distances, line_function


def slope_change(distances):
    # First derivative (slope between consecutive points)
    first_deriv = np.diff(distances)

    # Second derivative (change in slope)
    second_deriv = np.diff(first_deriv)

    # Pad to match original length
    second_deriv_padded = np.concatenate([[0], second_deriv, [0]])

    return second_deriv_padded


# Create a new dataframe grouped by 3D label
def calculate_3d_properties(df_3d_props):
    # Optional: add number of slices per 3D cell
    raw_cols = [c for c in df_3d_props.columns if c.startswith("raw_")]

    df_3d_props["num_slices"] = df_3d_props["labels_2d"].apply(len)
    init_arrays = lambda n: [0] * n
    for col in [
        "volumes_break_score",
        "final_break_score",
        "break_score_up",
        "break_score_down",
        "intensity_break_score",
    ]:
        df_3d_props[col] = df_3d_props["num_slices"].apply(init_arrays)

    if raw_cols:

        def max_intensity(row):
            per_channel = [row[col] for col in raw_cols]
            return [max(values) for values in zip(*per_channel)]

    else:

        def max_intensity(row):
            return [0] * row["num_slices"]

    df_3d_props["nuclei_intensity"] = df_3d_props.apply(max_intensity, axis=1)

    # itterate over every row, look at the volumes, find cells where the pattern is big small big
    for idx, row in df_3d_props.iterrows():
        volumes = row["volumes"]
        intensities = row["nuclei_intensity"]
        if len(volumes) < 5:
            continue  # At least 5 slices to break something

        for i in range(1, len(volumes) - 1):
            df_3d_props.at[idx, "volumes_break_score"][i] = break_score(volumes, i)
            df_3d_props.at[idx, "intensity_break_score"][i] = break_score(
                intensities, i
            )
            # multiply both scores to get a final score

        # Calculate a line based on first 3 points and calculate distance from this line for other points
        z_positions = row["z_positions"]
        x_positions = row["x_centroids"]
        y_positions = row["y_centroids"]
        line_distance_up, _ = point_line_distance(z_positions, x_positions, y_positions)
        # # get delta between consecutive points
        # delta_line_distance_up = abs(np.diff(line_distance_up))
        # break_score_up = [0] + [score / 1 for score in delta_line_distance_up]
        break_score_up = abs(slope_change(line_distance_up))
        df_3d_props.at[idx, "break_score_up"] = break_score_up

        # Calculate a line based on last 3 points and calculate distance from this line for other points
        line_distance_down, _ = point_line_distance(
            z_positions[::-1], x_positions[::-1], y_positions[::-1]
        )
        line_distance_down = line_distance_down[::-1]
        # delta_line_distance_down = abs(np.diff(line_distance_down))
        # break_score_down = [0] + [score / 1 for score in delta_line_distance_down]
        break_score_down = abs(slope_change(line_distance_down))
        df_3d_props.at[idx, "break_score_down"] = break_score_down

        # calculate final break score by multiplying all scores
        final_scores = []
        for v_score, i_score, up_score, down_score in zip(
            df_3d_props.at[idx, "volumes_break_score"],
            df_3d_props.at[idx, "intensity_break_score"],
            df_3d_props.at[idx, "break_score_up"],
            df_3d_props.at[idx, "break_score_down"],
        ):
            final_score = np.max([up_score, down_score]) * v_score * i_score
            final_scores.append(final_score)
        df_3d_props.at[idx, "final_break_score"] = final_scores

    return df_3d_props


def make_data_frame_3d(data):
    raw_cols = [c for c in data.columns if c.startswith("raw_")]

    agg_map = {
        "label": list,
        "z": list,
        "y": list,
        "x": list,
        "volume": list,
    }
    agg_map.update({col: list for col in raw_cols})

    data = data.groupby("3d_label").agg(agg_map).reset_index()

    rename_map = {
        "label": "labels_2d",
        "z": "z_positions",
        "y": "y_centroids",
        "x": "x_centroids",
        "volume": "volumes",
    }
    data = data.rename(columns=rename_map)

    return data


def stitch_loop(df_final, threshold=2.5):
    # Make 3D dataframe from current df_final state
    uncut_data = make_data_frame_3d(df_final)

    # Calculate break scores
    df_3d_props = calculate_3d_properties(uncut_data)

    # # This code can show how it is cutting during debugging
    # # Drop num_slices
    # df_3d_props_long = df_3d_props.drop(columns=["num_slices"], errors="ignore")

    # # Add slice index to keep alignment after explode
    # df_3d_props_long["slice_idx"] = df_3d_props_long["volumes"].apply(lambda v: list(range(len(v))))

    # # Identify list-like columns (excluding the key column)
    # list_cols = [
    #     c for c in df_3d_props_long.columns
    #     if c != "3d_label" and df_3d_props_long[c].apply(lambda v: isinstance(v, (list, tuple, np.ndarray))).all()
    # ]

    # # Explode all list-like columns together (keeps rows aligned)
    # df_3d_props_long = df_3d_props_long.explode(list_cols, ignore_index=True)
    # display(df_3d_props_long[df_3d_props_long["3d_label"] == 409])
    # Get the maximum existing 3D label to continue numbering
    new_label_counter = df_3d_props["3d_label"].max() + 1

    breaks_found = 0  # Track if any breaks were made

    cut_cells = []
    # Break cells at slices with break score above threshold
    for idx, row in df_3d_props.iterrows():
        break_scores = row["final_break_score"]
        labels_2d = row["labels_2d"]

        # Only consider breaks in middle slices (skip first 3 and last 3)
        # Need at least 3 slices on each side for valid detection
        if len(labels_2d) < 7:  # Too short to have valid breaks
            continue

        # Mask out first 3 and last 3 positions
        masked_scores = np.array(break_scores, dtype=float)
        masked_scores[:3] = 0  # First 3 slices get score 0
        masked_scores[-3:] = 0  # Last 3 slices get score 0

        # If no breaks above threshold, skip this cell
        if max(masked_scores) < threshold:
            continue

        breaks_found += 1

        # Find slice with highest break score
        max_break = max(masked_scores)
        break_position = [
            i for i, score in enumerate(masked_scores) if score == max_break
        ][0]

        # Get the 2D labels
        labels_2d = row["labels_2d"]

        # All slices after and including break get a new 3D label
        for i in range(break_position, len(labels_2d)):
            label_2d = labels_2d[i]
            df_final.loc[df_final["label"] == label_2d, "3d_label"] = new_label_counter

        cut_cells.append(row["3d_label"])
        cut_cells.append(new_label_counter)
        new_label_counter += 1

    return df_final, breaks_found, cut_cells

def stitch_3D(image1, image2=None, mask = None, threshold = 2.5):
    if mask is None:
        mask = utils.segment(image1, model)

    if image2 is not None:
        df_final, unique_mask = get_mask_properties(mask, image1, image2)
    else:
        df_final, unique_mask = get_mask_properties(mask, image1)
    # Initial IOU-based stitching
    IOU_stitched_df, IOU_stitched_mask = IOU_stitching(df_final, unique_mask)
    stitched_df = IOU_stitched_df.copy()

    # Iterative break and restitching
    max_iterations = 10
    iteration = 0
    all_cut_cells = []
    while iteration < max_iterations:
            iteration += 1
        print(f"Stitching iteration {iteration}...")
        stitched_df, breaks_found, cut_cells = stitch_loop(stitched_df, threshold=threshold)
        all_cut_cells.extend(cut_cells)
        print(f"Breaks made this iteration: {breaks_found}")

        if breaks_found == 0:
            print("No more breaks found. Stitching complete.")
            break

    # Final unique mask creation
    mask_3d_fixed = np.zeros_like(unique_mask)
    for idx, row in stitched_df.iterrows():
        z = int(row["z"])
        label_3d = row["3d_label"]
        mask_3d_fixed[z][unique_mask[z] == row["label"]] = label_3d

    print(f"Total unique 3D cells found: {stitched_df['3d_label'].nunique()} after stitching")

    return mask_3d_fixed, IOU_stitched_mask, stitched_df, IOU_stitched_df, all_cut_cells

In [ ]:
import os
output_directory = r"C:\Users\6331823\Local SSD\Fake_data"
# fake data stitching
image = tifffile.imread(os.path.join(output_directory, "realistic_organoid.tif"))
perfect_organoid = tifffile.imread(os.path.join(output_directory, "perfect_organoid.tif"))

image_wt = image_crc = image
# make a fake channel layer at axis 1
mask = tifffile.imread(
    os.path.join(output_directory, "realistic_organoid_segmented.tif")
)
perfect_mask = tifffile.imread(os.path.join(output_directory, "perfect_mask.tif"))

mask_3d_fixed, IOU_stitched_mask, stitched_df, IOU_stitched_df, all_cut_cells = stitch_3D(image_wt, image_crc, mask=mask, threshold=2.5)
print(f"actual amount of cells: {len(np.unique(perfect_mask)) - 1}")

# create a mask that only has cells that were cut
cut_cells_mask = np.zeros_like(mask_3d_fixed)
for cell_label in all_cut_cells:
    cut_cells_mask[mask_3d_fixed == cell_label] = cell_label

new_labels = np.zeros_like(mask_3d_fixed)
for idx, row in new_df.iterrows():
    z = int(row["z"])
    label_3d = row["3d_label"]
    coords_array = np.array(list(row["coords_set"]))

    if len(coords_array) > 0:
        y_coords = coords_array[:, 0].astype(int)
        x_coords = coords_array[:, 1].astype(int)
        new_labels[z, y_coords, x_coords] = label_3d
viewer = napari.Viewer()
scale = (2.5, 0.64, 0.64)
viewer.add_image(image, scale=scale, name="image", visible=False)
viewer.add_image(perfect_organoid, name="perfect organoid", scale=scale, visible=False)
viewer.add_labels(perfect_mask, name="perfect mask", scale=scale, visible=False)
viewer.add_labels(mask_3d_fixed, name="Final stitched mask", scale=scale)
viewer.add_labels(IOU_stitched_mask, name="IOU stitched mask", scale=scale, visible=False)
viewer.add_labels(cut_cells_mask, name="cut cells", scale=scale, visible=False)
viewer.add_labels(test, name = 'test', scale=scale, visible=False)
viewer.add_labels(new_labels, name="new_labels", scale=scale, visible=False)

Starting IOU-based stitching...
Total unique 3D cells found: 178 via IOU stitching
Stitching iteration 1...
Breaks made this iteration: 20
Stitching iteration 2...
Breaks made this iteration: 11
Stitching iteration 3...
Breaks made this iteration: 1
Stitching iteration 4...
Breaks made this iteration: 0
No more breaks found. Stitching complete.
Total unique 3D cells found: 210 after stitching
actual amount of cells: 200

In [56]:
test.shape

(77, 300, 300)

In [78]:
# For all cut cells, find if which other cut cells they are touching in 3D space
props = regionprops(cut_cells_mask)
new_df = stitched_df.copy()

properties = []
for prop in props:
    label = prop.label
    coords_3d = prop.coords # (z, y, x)
    # filter only coords that are highest and lowest z positions
    selected_coords_3d = coords_3d[
        (coords_3d[:, 0] == coords_3d[:, 0].min()) | (coords_3d[:, 0] == coords_3d[:, 0].max())
    ]   
    centeroid = prop.centroid
    properties.append({
    "label": label,
    "selected_coords_3d": selected_coords_3d,
    "coords_3d": coords_3d,
    "centeroid": centeroid
    })
properties = pd.DataFrame(properties)

properties["touching_cells"] = None

neighbor_offsets = [(-1, 0, 0), (1, 0, 0)]

for idx, cell in properties.iterrows():
    centeroid = cell["centeroid"]
    properties["distance"] = properties["centeroid"].apply(
        lambda x: np.sqrt(
            (x[0] - centeroid[0]) ** 2
            + (x[1] - centeroid[1]) ** 2
            + (x[2] - centeroid[2]) ** 2
        )
    )
    closest_cells = properties.sort_values("distance").iloc[1:6]

    touching_cells = []
    cell_coords_set = set(map(tuple, cell["selected_coords_3d"]))
    for _, other_cell in closest_cells.iterrows():
        other_coords = set(map(tuple, other_cell["coords_3d"]))
        if any(
            (z + dz, y, x) in other_coords
            for z, y, x in cell_coords_set
            for dz, _, _ in neighbor_offsets
        ):
            touching_cells.append(other_cell["label"])

    properties.at[idx, "touching_cells"] = touching_cells

# remove distance column
properties = properties.drop(columns=["distance"])
properties
# get a new dataframe with all combinations of touching cells
touching_pairs = []
for idx, cell in properties.iterrows():
    label = cell["label"]
    for touching_label in cell["touching_cells"]:
        if label < touching_label:  # Avoid duplicates
            cell_1_coords = cell["coords_3d"]
            cell_2_coords = properties[properties["label"] == touching_label]["coords_3d"].values[0]
            cell_1_centeroid = cell["centeroid"]
            cell_2_centeroid = properties[properties["label"] == touching_label]["centeroid"].values[0]
            if cell_1_centeroid[0] < cell_2_centeroid[0]:
                touching_pairs.append({"cell_1": label, "cell_2": touching_label,
                                    "cell_1_coords": cell_1_coords,
                                    "cell_2_coords": cell_2_coords,
                                    "cell_1_centeroid": cell_1_centeroid,
                                    "cell_2_centeroid": cell_2_centeroid,
                                    })
            else:
                touching_pairs.append({"cell_1": touching_label, "cell_2": label,
                                    "cell_1_coords": cell_2_coords,
                                    "cell_2_coords": cell_1_coords,
                                    "cell_1_centeroid": cell_2_centeroid,
                                    "cell_2_centeroid": cell_1_centeroid,
                                    })


def slice_centroids_df(coords_3d):
    df = pd.DataFrame(coords_3d, columns=["z", "y", "x"])
    out = (
        df.groupby("z")[["y", "x"]]
        .mean()
        .reset_index()
        .assign(y=lambda d: d["y"].astype(float), x=lambda d: d["x"].astype(float))
    )
    return list(out.itertuples(index=False, name=None))

def check_split_cells(centroids_2d, pred_point_1, pred_point_2, pair):
    last_z = centroids_2d[-1][0]
    cell_1_last_slice = np.array(
        [coord for coord in pair["cell_1_coords"] if coord[0] == last_z]
    )
    original_centroid = centroids_2d[-1]
    original_distance_1 = np.sqrt(
        (original_centroid[1] - y_last_slice_line_1)**2 + 
        (original_centroid[2] - x_last_slice_line_1)**2
    )

    # Create splitting line perpendicular to the line between the two predicted points
    # Direction vector between predicted points
    direction = pred_point_2 - pred_point_1
    # Perpendicular vector (rotate 90 degrees)
    normal = direction / (np.linalg.norm(direction) + 1e-8)
    # Midpoint between predicted points
    midpoint = (pred_point_1 + pred_point_2) / 2

    part_1_coords = []
    part_2_coords = []

    for coord in cell_1_last_slice:
        z, y, x = coord
        point = np.array([y, x])
        # Vector from midpoint to this point
        to_point = point - midpoint
        # Dot product determines which side of the line
        side = np.dot(to_point, normal)

        if side <= 0:
            part_1_coords.append(coord)
        else:
            part_2_coords.append(coord)

    min_size = max(
        3, len(cell_1_last_slice) * 0.1
    )  # At least 10% of pixels or 3 pixels

    if len(part_1_coords) < min_size or len(part_2_coords) < min_size:
        print(f"  Warning: Split too unbalanced ({len(part_1_coords)} vs {len(part_2_coords)} pixels)")
        return None

    # Calculate new centroids
    part_1_coords = np.array(part_1_coords)
    part_2_coords = np.array(part_2_coords)

    centroid_1 =  np.mean(part_1_coords[:, 1:], axis=0)  # (y, x)
    centroid_2 = np.mean(part_2_coords[:, 1:], axis=0)  # (y, x)

    # Calculate distances from new centroids to predicted points
    dist_c1_to_pred1 = np.sqrt(
        (centroid_1[0] - pred_point_1[0]) ** 2
        + (centroid_1[1] - pred_point_1[1]) ** 2
    )
    dist_c2_to_pred2 = np.sqrt(
        (centroid_2[0] - pred_point_2[0]) ** 2
        + (centroid_2[1] - pred_point_2[1]) ** 2
    )

    # Check if splitting improves the fit
    avg_new_distance = (dist_c1_to_pred1 + dist_c2_to_pred2) / 2

    print(f"  Cell {pair['cell_1']} & {pair['cell_2']}:")
    if avg_new_distance < original_distance_1:
        print(
            f"    ✓ Splitting improves fit! (reduction: {original_distance_1 - avg_new_distance:.2f})"
        )
        return(part_1_coords, part_2_coords)
    else:
        print(f"    ✗ Splitting does not improve fit")
        return None

for pair in touching_pairs:
    centroids_2d_1 = slice_centroids_df(pair["cell_1_coords"])
    centroids_2d_2 = slice_centroids_df(pair["cell_2_coords"])

    distances_1, line_1 = point_line_distance(
        [c[0] for c in centroids_2d_1],  # z
        [c[2] for c in centroids_2d_1],  # x
        [c[1] for c in centroids_2d_1],  # y
        points=(0, -1),
    )
    distances_2, line_2 = point_line_distance(
        [c[0] for c in centroids_2d_2][::-1],  # z
        [c[2] for c in centroids_2d_2][::-1],  # x
        [c[1] for c in centroids_2d_2][::-1],  # y
        points=(0, -1),
    )
    x_last_slice_line_1, y_last_slice_line_1 = line_1(centroids_2d_1[-1][0])
    x_last_slice_line_2, y_last_slice_line_2 = line_2(centroids_2d_2[-1][0])
    # if the predicted point is inside the cell_1 coords, print("Predicted point is inside cell 1")
    cell_1_coords_set = set(map(tuple, pair["cell_1_coords"]))
    cell_2_coords_set = set(map(tuple, pair["cell_2_coords"]))

    # Check if both predicted points are inside the overlapping slice
    pred_in_cell_1_line_1 = (
        centroids_2d_1[-1][0],
        int(round(y_last_slice_line_1)),
        int(round(x_last_slice_line_1)),
    ) in cell_1_coords_set
    # print(int(round(y_last_slice_line_1)), int(round(x_last_slice_line_1)))
    # print(pair["cell_1_coords"][centroids_2d_1[-1][0] == pair["cell_1_coords"][:,0]])
    pred_in_cell_1_line_2 = (
        centroids_2d_1[-1][0],
        int(round(y_last_slice_line_2)),
        int(round(x_last_slice_line_2)),
    ) in cell_1_coords_set

    if pred_in_cell_1_line_1 and pred_in_cell_1_line_2:
        # Check minimum distance between predicted points
        pred_point_1 = np.array([y_last_slice_line_1, x_last_slice_line_1])
        pred_point_2 = np.array([y_last_slice_line_2, x_last_slice_line_2])
        distance_between_preds = np.linalg.norm(pred_point_2 - pred_point_1)

        if distance_between_preds < 1:  # Minimum 1 pixel apart
            continue

        # split the cell 1 coords of this last z slice into two parts, perpendicular to the line between the two predicted points
        # Get the last z slice coords for both cells

        result = check_split_cells(
            centroids_2d_1, pred_point_1, pred_point_2, pair
        )
        if result is None:
            continue
        part_1_coords, part_2_coords = result
        # Update the new_df to reflect the split
        last_z = centroids_2d_1[-1][0]

        # Convert part coords to (y, x) tuples for coords_set
        part_1_coords_2d = set(map(tuple, part_1_coords[:, 1:]))  # (y, x)
        part_2_coords_2d = set(map(tuple, part_2_coords[:, 1:]))  # (y, x)

        # Find the row(s) for cell_1 at last_z and update coords_set
        cell_1_mask = (new_df["3d_label"] == pair["cell_1"]) & (new_df["z"] == last_z)
        if cell_1_mask.any():
            # Overwrite coords_set for cell_1 at last z slice - assign to each row
            for idx in new_df[cell_1_mask].index:
                new_df.at[idx, "coords_set"] = part_1_coords_2d

        # Add a new row for cell_2 at last z slice
        new_row = new_df[cell_1_mask].iloc[0].copy()
        new_row["3d_label"] = pair["cell_2"]
        new_row["coords_set"] = part_2_coords_2d
        new_row["volume"] = len(part_2_coords_2d)
        new_df = pd.concat([new_df, pd.DataFrame([new_row])], ignore_index=True)

  Cell 68 & 199:
    ✗ Splitting does not improve fit
  Cell 69 & 180:
    ✗ Splitting does not improve fit
  Cell 71 & 181:
    ✓ Splitting improves fit! (reduction: 1.38)
  Cell 72 & 200:
    ✗ Splitting does not improve fit
  Cell 76 & 201:
    ✗ Splitting does not improve fit
  Cell 78 & 185:
    ✓ Splitting improves fit! (reduction: 4.51)
  Cell 79 & 202:
    ✗ Splitting does not improve fit
  Cell 80 & 187:
    ✗ Splitting does not improve fit
  Cell 83 & 188:
    ✓ Splitting improves fit! (reduction: 0.27)
  Cell 86 & 189:
    ✗ Splitting does not improve fit
  Cell 87 & 190:
    ✗ Splitting does not improve fit
  Cell 89 & 203:
    ✓ Splitting improves fit! (reduction: 6.18)
  Cell 91 & 192:
    ✓ Splitting improves fit! (reduction: 3.37)
  Cell 93 & 193:
    ✗ Splitting does not improve fit
  Cell 108 & 198:
    ✓ Splitting improves fit! (reduction: 0.02)
  Cell 210 & 179:
    ✗ Splitting does not improve fit
  Cell 200 & 182:
    ✓ Splitting improves fit! (reduction: 1.80)
  Cell 193 & 208:
    ✗ Splitting does not improve fit
  Cell 196 & 209:
    ✓ Splitting improves fit! (reduction: 2.62)
  Cell 199 & 210:
    ✗ Splitting does not improve fit

In [86]:
new_df[new_df["3d_label"] == 181]

,label,z,y,x,bounding_box,volume,coords_set,raw_wt,raw_crc,3d_label
830,831,34.0,31.991453,106.880342,"(34, 28, 98, 35, 37, 117)",117.0,"{(32, 101), (33, 100), (32, 110), (30, 110), (...",37.991453,37.991453,181
854,855,35.0,32.020408,106.938776,"(35, 27, 97, 36, 38, 118)",147.0,"{(32, 101), (33, 100), (27, 114), (35, 97), (3...",57.782313,57.782313,181
881,882,36.0,32.071006,106.804734,"(36, 26, 96, 37, 39, 119)",169.0,"{(32, 101), (33, 100), (27, 114), (35, 97), (3...",76.118343,76.118343,181
905,906,37.0,32.053254,106.863905,"(37, 26, 96, 38, 39, 119)",169.0,"{(32, 101), (33, 100), (27, 114), (35, 97), (3...",91.497041,91.497041,181
930,931,38.0,32.017647,106.841176,"(38, 26, 96, 39, 39, 119)",170.0,"{(32, 101), (33, 100), (27, 114), (35, 97), (3...",94.417647,94.417647,181
954,955,39.0,31.888889,107.024691,"(39, 26, 96, 40, 38, 119)",162.0,"{(32, 101), (33, 100), (27, 114), (35, 97), (3...",87.111111,87.111111,181
980,981,40.0,31.794702,107.006623,"(40, 26, 96, 41, 38, 118)",151.0,"{(32, 101), (33, 100), (27, 114), (35, 97), (3...",69.397351,69.397351,181
1006,1007,41.0,31.626866,107.567164,"(41, 27, 98, 42, 37, 118)",134.0,"{(32, 101), (33, 100), (27, 114), (32, 110), (...",48.283582,48.283582,181
1032,1033,42.0,31.489796,109.551020,"(42, 28, 100, 43, 36, 119)",98.0,"{(33, 100), (32, 110), (30, 110), (33, 109), (...",31.989796,31.989796,181
1864,808,33.0,33.415385,108.692308,"(33, 29, 100, 34, 39, 118)",74.0,"{(32, 101), (30, 107), (30, 113), (32, 104), (...",24.761538,24.761538,181

In [5]:
cut_cells_data = stitched_df[stitched_df["3d_label"].isin(all_cut_cells)]
simple_data = cut_cells_data[["3d_label", "z", "y", "x"]].copy()
summary_3d = []
neighbor_offsets = [(-1, 0, 0), (1, 0, 0)]

for cell in all_cut_cells:
    cell_data = cut_cells_data[cut_cells_data["3d_label"] == cell]
    centeroid = cell_data[["z", "y", "x"]].mean().values
    # Flatten all coords_set into a single set, adding z coordinate from each row
    coords_3d_flat = set()
    for idx, row in cell_data.iterrows():
        z = int(round(row["z"]))
        for y, x in row["coords_set"]:
            coords_3d_flat.add((z, y, x))

    summary_3d.append(
        {
            "3d_label": cell,
            "num_slices": len(cell_data),
            "centeroid_z": centeroid[0],
            "centeroid_y": centeroid[1],
            "centeroid_x": centeroid[2],
            "coords_3d": coords_3d_flat,  # Now stores a single set, not a list of sets
        }
    )
summary_3d = pd.DataFrame(summary_3d)
summary_3d["touching_cells"] = None

for cell in all_cut_cells:
    cell_data = summary_3d[summary_3d["3d_label"] == cell]
    # calculate distance to all other cells in summary_3d
    centeroid = cell_data[["centeroid_z", "centeroid_y", "centeroid_x"]].values[0]
    summary_3d["distance"] = summary_3d.apply(
        lambda row: np.sqrt(
            (row["centeroid_z"] - centeroid[0]) ** 2
            + (row["centeroid_y"] - centeroid[1]) ** 2
            + (row["centeroid_x"] - centeroid[2]) ** 2
        ),
        axis=1,
    )

    closest_cells = (
        summary_3d[summary_3d["3d_label"] != cell]
        .sort_values("distance")[1:6]
    )
    touching_cells = []
    cell_coords_set = cell_data["coords_3d"].values[0]  # Already a set

    for _, other_cell in closest_cells.iterrows():
        other_coords = other_cell["coords_3d"]  # Already a set
        if any(
            (z + dz, y, x) in other_coords
            for z, y, x in cell_coords_set
            for dz, _, _ in neighbor_offsets
        ):
            touching_cells.append(other_cell["3d_label"])
    # Find the index where 3d_label == cell and assign the value
    cell_idx = summary_3d[summary_3d["3d_label"] == cell].index[0]
    summary_3d.at[cell_idx, "touching_cells"] = touching_cells

# Remove the distance column
summary_3d = summary_3d.drop(columns=["distance"])
display(summary_3d.head())

,3d_label,num_slices,centeroid_z,centeroid_y,centeroid_x,coords_3d,touching_cells
0,68,7,26.0,198.961090,256.865027,"{(26, 203, 255), (28, 200, 261), (27, 199, 253...",[199]
1,179,4,40.5,188.234340,267.886611,"{(39, 182, 268), (39, 193, 268), (41, 182, 270...",[204]
2,69,9,28.0,115.270187,263.993250,"{(26, 117, 261), (26, 120, 266), (25, 116, 265...",[]
3,180,8,36.5,110.322110,268.207891,"{(39, 107, 265), (40, 111, 269), (35, 118, 273...",[108]
4,71,9,29.0,35.761089,111.494037,"{(31, 37, 105), (28, 33, 111), (26, 33, 118), ...",[]

In [40]:
# real data stitching
image = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\cropped\Frame-0.tif"
)
print(image.shape)
crc_image = image[:, 0]
print(crc_image.shape)
wt_image = image[:, 1]
mask = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\Frame-0_segmented.tif"
)

mask_3d_fixed, IOU_stitched_mask, stitched_df, IOU_stitched_df, _ = stitch_3D(
    wt_image, crc_image, mask=mask, threshold=2.5
)

viewer = napari.Viewer(ndisplay=3)
scale = (2.5, 0.64, 0.64)
viewer.add_image(wt_image, scale=scale, name="wt image", visible=False, blending="additive")
viewer.add_image(crc_image, scale=scale, name="crc image", visible=False, blending="additive")
viewer.add_labels(mask_3d_fixed, name="Final stitched mask", scale=scale)
viewer.add_labels(
    IOU_stitched_mask, name="IOU stitched mask", scale=scale, visible=False
)

(63, 3, 356, 370)
(63, 356, 370)
Starting IOU-based stitching...
Total unique 3D cells found: 328 via IOU stitching
Stitching iteration 1...
Breaks made this iteration: 37
Stitching iteration 2...
Breaks made this iteration: 11
Stitching iteration 3...
Breaks made this iteration: 2
Stitching iteration 4...
Breaks made this iteration: 1
Stitching iteration 5...
Breaks made this iteration: 0
No more breaks found. Stitching complete.
Total unique 3D cells found: 379 after stitching

RuntimeError: sequence argument must have length equal to input rank

In [50]:
image = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\cropped\Frame-10.tif"
).astype(np.uint16)
image = image[:,:,:,0:606]
print(image.shape)
crc_image = image[:, 0]
wt_image = image[:, 1]

mask = tifffile.imread(
    r"C:\Users\6331823\Local SSD\Data_Elise\EM_Exp007_Imaging_20x_2025-11-21_Maria_Elise_14.47.50_CZC34578YN_F24\segmented\Frame-10_masks.tif"
)
print(mask.shape)
mask_3d_fixed, IOU_stitched_mask, stitched_df, IOU_stitched_df, _ = stitch_3D(
    wt_image, crc_image, mask=mask, threshold=2.5
)


viewer = napari.Viewer(ndisplay=3)
scale = (2.5, 0.64, 0.64)
viewer.add_image(
    wt_image, scale=scale, name="wt image", visible=False, blending="additive"
)
viewer.add_image(
    crc_image, scale=scale, name="crc image", visible=False, blending="additive"
)
viewer.add_labels(mask_3d_fixed, name="Final stitched mask", scale=scale)
viewer.add_labels(
    IOU_stitched_mask, name="IOU stitched mask", scale=scale, visible=False
)

(92, 3, 528, 606)
(92, 528, 606)
Starting IOU-based stitching...
Total unique 3D cells found: 1205 via IOU stitching
Stitching iteration 1...

,3d_label,labels_2d,z_positions,y_centroids,x_centroids,volumes,raw_wt,raw_crc,volumes_break_score,final_break_score,break_score_up,break_score_down,intensity_break_score,nuclei_intensity,slice_idx
2858,409,7436,31.0,56.189189,142.72973,37.0,137.27027,105.918919,0,0.0,0.0,0.0,0,137.27027,0
2859,409,7856,32.0,56.769231,141.974359,78.0,152.064103,107.564103,1.009533,1.55159,0.587063,1.54715,0.9934,152.064103,1
2860,409,8289,33.0,56.017699,142.371681,113.0,159.938053,107.292035,1.014018,0.887324,0.879655,0.189748,0.994773,159.938053,2
2861,409,8730,34.0,55.37234,142.404255,94.0,167.340426,106.531915,2.122906,1.96183,0.993675,0.774508,0.930007,167.340426,3
2862,409,9182,35.0,54.145161,143.354839,124.0,162.830645,106.758065,1.219953,0.334827,0.276573,0.227497,0.992357,162.830645,4
2863,409,9646,36.0,53.064815,144.018519,108.0,157.231481,106.296296,1.764746,0.078103,0.010445,0.042426,1.043161,157.231481,5
2864,409,10114,37.0,51.902913,144.563107,103.0,147.563107,106.631068,1.940239,2.60235,1.132493,0.63896,1.184336,147.563107,6
2865,409,10583,38.0,51.060976,143.439024,82.0,144.841463,106.378049,3.061273,4.338162,1.152813,0.613306,1.229263,144.841463,7
2866,409,11056,39.0,49.589474,143.336842,95.0,141.894737,105.968421,2.280776,1.89624,0.558145,0.649102,1.280849,141.894737,8
2867,409,11538,40.0,48.847328,143.557252,131.0,146.832061,107.328244,1.199464,0.45802,0.319234,0.044413,1.196159,146.832061,9
2868,409,12026,41.0,48.680851,144.262411,141.0,153.361702,106.836879,1.093808,1.122745,0.788492,0.936146,1.09647,153.361702,10
2869,409,12519,42.0,49.061644,144.205479,146.0,154.109589,106.226027,1.098048,2.68786,2.268305,0.79342,1.079155,154.109589,11
2870,409,13017,43.0,48.448598,146.560748,107.0,153.158879,106.813084,2.116866,10.082937,4.422694,1.700739,1.076978,153.158879,12
2871,409,13519,44.0,49.837349,144.222892,166.0,150.96988,107.072289,0,0.0,0.0,0.0,0,150.96988,13

Breaks made this iteration: 182
Stitching iteration 2...

,3d_label,labels_2d,z_positions,y_centroids,x_centroids,volumes,raw_wt,raw_crc,volumes_break_score,final_break_score,break_score_up,break_score_down,intensity_break_score,nuclei_intensity,slice_idx
2516,409,7436,31.0,56.189189,142.72973,37.0,137.27027,105.918919,0,0.0,0.0,0.0,0,137.27027,0
2517,409,7856,32.0,56.769231,141.974359,78.0,152.064103,107.564103,0.754109,1.307181,0.587063,1.744928,0.9934,152.064103,1
2518,409,8289,33.0,56.017699,142.371681,113.0,159.938053,107.292035,0.757459,0.66282,0.879655,0.366468,0.994773,159.938053,2
2519,409,8730,34.0,55.37234,142.404255,94.0,167.340426,106.531915,1.585785,1.465463,0.993675,0.296715,0.930007,167.340426,3
2520,409,9182,35.0,54.145161,143.354839,124.0,162.830645,106.758065,0.793704,0.29756,0.276573,0.377788,0.992357,162.830645,4
2521,409,9646,36.0,53.064815,144.018519,108.0,157.231481,106.296296,1.094993,0.052623,0.010445,0.048113,0.998849,157.231481,5
2522,409,10114,37.0,51.902913,144.563107,103.0,147.563107,106.631068,0,0.0,0.0,0.0,0,147.563107,6

Breaks made this iteration: 60
Stitching iteration 3...

,3d_label,labels_2d,z_positions,y_centroids,x_centroids,volumes,raw_wt,raw_crc,volumes_break_score,final_break_score,break_score_up,break_score_down,intensity_break_score,nuclei_intensity,slice_idx
2463,409,7436,31.0,56.189189,142.72973,37.0,137.27027,105.918919,0,0.0,0.0,0.0,0,137.27027,0
2464,409,7856,32.0,56.769231,141.974359,78.0,152.064103,107.564103,0.754109,1.307181,0.587063,1.744928,0.9934,152.064103,1
2465,409,8289,33.0,56.017699,142.371681,113.0,159.938053,107.292035,0.757459,0.66282,0.879655,0.366468,0.994773,159.938053,2
2466,409,8730,34.0,55.37234,142.404255,94.0,167.340426,106.531915,1.585785,1.465463,0.993675,0.296715,0.930007,167.340426,3
2467,409,9182,35.0,54.145161,143.354839,124.0,162.830645,106.758065,0.793704,0.29756,0.276573,0.377788,0.992357,162.830645,4
2468,409,9646,36.0,53.064815,144.018519,108.0,157.231481,106.296296,1.094993,0.052623,0.010445,0.048113,0.998849,157.231481,5
2469,409,10114,37.0,51.902913,144.563107,103.0,147.563107,106.631068,0,0.0,0.0,0.0,0,147.563107,6

Breaks made this iteration: 27
Stitching iteration 4...

,3d_label,labels_2d,z_positions,y_centroids,x_centroids,volumes,raw_wt,raw_crc,volumes_break_score,final_break_score,break_score_up,break_score_down,intensity_break_score,nuclei_intensity,slice_idx
2459,409,7436,31.0,56.189189,142.72973,37.0,137.27027,105.918919,0,0.0,0.0,0.0,0,137.27027,0
2460,409,7856,32.0,56.769231,141.974359,78.0,152.064103,107.564103,0.754109,1.307181,0.587063,1.744928,0.9934,152.064103,1
2461,409,8289,33.0,56.017699,142.371681,113.0,159.938053,107.292035,0.757459,0.66282,0.879655,0.366468,0.994773,159.938053,2
2462,409,8730,34.0,55.37234,142.404255,94.0,167.340426,106.531915,1.585785,1.465463,0.993675,0.296715,0.930007,167.340426,3
2463,409,9182,35.0,54.145161,143.354839,124.0,162.830645,106.758065,0.793704,0.29756,0.276573,0.377788,0.992357,162.830645,4
2464,409,9646,36.0,53.064815,144.018519,108.0,157.231481,106.296296,1.094993,0.052623,0.010445,0.048113,0.998849,157.231481,5
2465,409,10114,37.0,51.902913,144.563107,103.0,147.563107,106.631068,0,0.0,0.0,0.0,0,147.563107,6

Breaks made this iteration: 4
Stitching iteration 5...

,3d_label,labels_2d,z_positions,y_centroids,x_centroids,volumes,raw_wt,raw_crc,volumes_break_score,final_break_score,break_score_up,break_score_down,intensity_break_score,nuclei_intensity,slice_idx
2459,409,7436,31.0,56.189189,142.72973,37.0,137.27027,105.918919,0,0.0,0.0,0.0,0,137.27027,0
2460,409,7856,32.0,56.769231,141.974359,78.0,152.064103,107.564103,0.754109,1.307181,0.587063,1.744928,0.9934,152.064103,1
2461,409,8289,33.0,56.017699,142.371681,113.0,159.938053,107.292035,0.757459,0.66282,0.879655,0.366468,0.994773,159.938053,2
2462,409,8730,34.0,55.37234,142.404255,94.0,167.340426,106.531915,1.585785,1.465463,0.993675,0.296715,0.930007,167.340426,3
2463,409,9182,35.0,54.145161,143.354839,124.0,162.830645,106.758065,0.793704,0.29756,0.276573,0.377788,0.992357,162.830645,4
2464,409,9646,36.0,53.064815,144.018519,108.0,157.231481,106.296296,1.094993,0.052623,0.010445,0.048113,0.998849,157.231481,5
2465,409,10114,37.0,51.902913,144.563107,103.0,147.563107,106.631068,0,0.0,0.0,0.0,0,147.563107,6

Breaks made this iteration: 1
Stitching iteration 6...

,3d_label,labels_2d,z_positions,y_centroids,x_centroids,volumes,raw_wt,raw_crc,volumes_break_score,final_break_score,break_score_up,break_score_down,intensity_break_score,nuclei_intensity,slice_idx
2459,409,7436,31.0,56.189189,142.72973,37.0,137.27027,105.918919,0,0.0,0.0,0.0,0,137.27027,0
2460,409,7856,32.0,56.769231,141.974359,78.0,152.064103,107.564103,0.754109,1.307181,0.587063,1.744928,0.9934,152.064103,1
2461,409,8289,33.0,56.017699,142.371681,113.0,159.938053,107.292035,0.757459,0.66282,0.879655,0.366468,0.994773,159.938053,2
2462,409,8730,34.0,55.37234,142.404255,94.0,167.340426,106.531915,1.585785,1.465463,0.993675,0.296715,0.930007,167.340426,3
2463,409,9182,35.0,54.145161,143.354839,124.0,162.830645,106.758065,0.793704,0.29756,0.276573,0.377788,0.992357,162.830645,4
2464,409,9646,36.0,53.064815,144.018519,108.0,157.231481,106.296296,1.094993,0.052623,0.010445,0.048113,0.998849,157.231481,5
2465,409,10114,37.0,51.902913,144.563107,103.0,147.563107,106.631068,0,0.0,0.0,0.0,0,147.563107,6

Breaks made this iteration: 0
No more breaks found. Stitching complete.
Total unique 3D cells found: 1479 after stitching

RuntimeError: sequence argument must have length equal to input rank

In [49]:
import numpy as np
from skimage.measure import regionprops


def centroid_accuracy(perfect_mask, mask_3d_fixed):
    perfect_mask = np.asarray(perfect_mask)
    pred_mask = np.asarray(mask_3d_fixed)
    if perfect_mask.shape != pred_mask.shape:
        raise ValueError("Masks must share shape")

    gt_props = regionprops(perfect_mask)
    hit_pred_labels = set()
    predicted_labels = np.array([])
    tp = fn = 0

    for prop in gt_props:
        centroid = np.rint(prop.centroid).astype(int)
        centroid = tuple(np.clip(centroid, 0, np.array(perfect_mask.shape) - 1))
        pred_label = pred_mask[centroid]
        predicted_labels = np.append(predicted_labels, pred_label)
        if pred_label > 0:
            tp += 1
            hit_pred_labels.add(int(pred_label))
        else:
            fn += 1

    pred_labels = set(np.unique(pred_mask))
    pred_labels.discard(0)
    fp = len(pred_labels - hit_pred_labels)
    fp_list = list(pred_labels - hit_pred_labels)
    merged_cells = len(predicted_labels) - len(np.unique(predicted_labels))

    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall else 0.0

    gt_binary = perfect_mask > 0
    pred_binary = pred_mask > 0
    intersection = np.count_nonzero(gt_binary & pred_binary)
    dice = (
        (2 * intersection) / (gt_binary.sum() + pred_binary.sum())
        if (gt_binary.sum() + pred_binary.sum())
        else 0.0
    )

    return {
        "true_positives": tp,
        "false_negatives": fn,
        "false_positives": fp,
        "merged_cells": merged_cells,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "voxel_dice": dice,
        "false_positive_labels": fp_list,
    }

# print(centroid_accuracy(perfect_mask, mask_3d_fixed))
# print(f"actual amount of cells: {len(np.unique(perfect_mask)) - 1}, predicted amount of cells: {len(np.unique(mask_3d_fixed)) - 1}")

In [114]:
# Method 2: Access the actual list value
cell = 79
intensity = (df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell][
    "nuclei_intensity"
].values[0])
intensity_break = (df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell]["intensity_break_score"].values[0])
volume = df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell]["volumes"].values[0]
volume_break = (df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell]["volumes_break_score"].values[0])
break_score_up = (df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell]["break_score_up"].values[0])
break_score_down = (df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell]["break_score_down"].values[0])
final_score = (df_3d_props_fixed[df_3d_props_fixed["3d_label"] == cell]["final_break_score"].values[0])

# create df of this and display
df_cell_detail = pd.DataFrame(
    {
        "slice": range(len(volume)),
        "volume": volume,
        "nuclei_intensity": intensity,
        "intensity_break_score": intensity_break,
        "volume_break_score": volume_break,
        "break_score_up": break_score_up,
        "break_score_down": break_score_down,
        "final_break_score": final_score,
    }
)



display(df_cell_detail)

,slice,volume,nuclei_intensity,intensity_break_score,volume_break_score,break_score_up,break_score_down,final_break_score
0,0,66.0,21.500000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,138.0,36.050725,1.653241,0.693132,0.138247,0.306124,0.350792
2,2,174.0,59.528736,1.016685,0.911613,0.427690,0.048959,0.396393
3,3,189.0,84.000000,0.843128,0.974217,0.002691,0.002606,0.002210
4,4,200.0,97.690000,0.879639,0.897750,0.087896,0.084598,0.069411
5,5,190.0,99.936842,0.854310,1.008310,0.373727,0.354597,0.321932
6,6,182.0,87.340659,0.894629,1.086825,0.066677,0.057741,0.064830
7,7,180.0,68.288889,0.000000,0.000000,0.000000,0.000000,0.000000

In [115]:
import napari

viewer = napari.Viewer(ndisplay=3)

# Create a shared color dictionary for specific labels
import numpy as np

wt_image = crc_image = tifffile.imread(os.path.join(output_directory, "realistic_organoid.tif"))
perfect_image = tifffile.imread(os.path.join(output_directory, "perfect_organoid.tif"))

# Generate colors for labels 0-max_label
max_label = max(mask_3d.max(), mask_3d_fixed.max())
np.random.seed(42)  # For reproducible colors
color_dict = {}
for i in range(max_label + 1):
    # Generate bright colors with full alpha
    color = np.random.rand(3)  # RGB only
    color = (
        color / color.max()
    )  # Normalize so at least one channel is at max brightness
    color_dict[i] = np.append(color, 0.8)  # Add full alpha

color_dict[0] = np.array([0, 0, 0, 0])  # Background transparent

# Apply to both layers
viewer.add_labels(
    mask_3d, name="3D_stitched_mask", scale=(2.5, 0.64, 0.64), colormap=color_dict
)
viewer.add_labels(
    mask_3d_fixed,
    name="3D_stitched_mask_fixed",
    scale=(2.5, 0.64, 0.64),
    colormap=color_dict,
)
viewer.add_labels(
    mask_3d_cuts,
    name="3D_stitched_mask_cuts",
    scale=(2.5, 0.64, 0.64),
    colormap=color_dict,
)

viewer.add_labels(
    unique_mask, name="original_mask", scale=(2.5, 0.64, 0.64), visible=False
)
viewer.add_image(
    crc_image,
    name="crc_image",
    scale=(2.5, 0.64, 0.64),
    blending="additive",
    visible=False,
)
viewer.add_image(
    wt_image,
    name="wt_image",
    scale=(2.5, 0.64, 0.64),
    blending="additive",
    visible=False,
)
viewer.add_image(
    perfect_image,
    name="perfect_image",
    scale=(2.5, 0.64, 0.64),
    blending="additive",
    visible=False,
)

viewer.add_labels(
    perfect_mask, name="perfect_mask", scale=(2.5, 0.64, 0.64), visible=False
)

c:\Users\6331823\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\utils\colormaps\colormap.py:447: UserWarning: color_dict did not provide a default color. Missing keys will be transparent. To provide a default color, use the key `None`, or provide a defaultdict instance.
  warn(
c:\Users\6331823\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\utils\colormaps\colormap.py:447: UserWarning: color_dict did not provide a default color. Missing keys will be transparent. To provide a default color, use the key `None`, or provide a defaultdict instance.
  warn(
c:\Users\6331823\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\utils\colormaps\colormap.py:447: UserWarning: color_dict did not provide a default color. Missing keys will be transparent. To provide a default color, use the key `None`, or provide a defaultdict instance.
  warn(

RuntimeError: sequence argument must have length equal to input rank

RuntimeError: sequence argument must have length equal to input rank

In [86]:
from skimage.draw import ellipsoid
import napari
import os
from scipy.ndimage import zoom, gaussian_filter

def make_cell(radius_Z, radius_Y, radius_X, intensity=255):
    """Create a binary ellipsoidal cell"""
    cell = ellipsoid(radius_Z, radius_Y, radius_X)
    cell = cell.astype(np.uint16) * intensity
    return cell


def paste_cell(volume, mask, cell, position, label):
    cz, cy, cx = position.astype(int)
    dz, dy, dx = cell.shape
    hz, hy, hx = dz // 2, dy // 2, dx // 2

    z0, z1 = max(0, cz - hz), min(volume.shape[0], cz + hz + 1)
    y0, y1 = max(0, cy - hy), min(volume.shape[1], cy + hy + 1)
    x0, x1 = max(0, cx - hx), min(volume.shape[2], cx + hx + 1)

    cell_z0 = hz - (cz - z0)
    cell_y0 = hy - (cy - y0)
    cell_x0 = hx - (cx - x0)

    subcell = cell[
        cell_z0 : cell_z0 + (z1 - z0),
        cell_y0 : cell_y0 + (y1 - y0),
        cell_x0 : cell_x0 + (x1 - x0),
    ]

    if subcell.size == 0:
        return False

    volume[z0:z1, y0:y1, x0:x1] = np.maximum(volume[z0:z1, y0:y1, x0:x1], subcell)
    mask[z0:z1, y0:y1, x0:x1][subcell > 0] = label
    return True

from scipy.ndimage import affine_transform


def _rotation_matrix(from_vec, to_vec):
    a = from_vec / (np.linalg.norm(from_vec) + 1e-8)
    b = to_vec / (np.linalg.norm(to_vec) + 1e-8)
    v = np.cross(a, b)
    c = np.dot(a, b)
    if np.isclose(c, 1.0):
        return np.eye(3)
    if np.isclose(c, -1.0):
        # 180° flip around any perpendicular axis
        perp = np.array([1.0, 0.0, 0.0])
        if np.allclose(a, perp):
            perp = np.array([0.0, 1.0, 0.0])
        v = perp - a * np.dot(perp, a)
        v /= np.linalg.norm(v)
        vx = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
        return np.eye(3) + 2 * vx @ vx
    vx = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    return np.eye(3) + vx + vx @ vx * ((1 - c) / (np.linalg.norm(v) ** 2 + 1e-8))


def orient_cell(cell, direction_vec):
    base = np.array([1.0, 0.0, 0.0])  # +z axis in (z, y, x) ordering
    pad = int(max(cell.shape) * 0.75)
    padded = np.pad(
        cell,
        ((pad, pad), (pad, pad), (pad, pad)),
        mode="constant",
        constant_values=0,
    )
    R = _rotation_matrix(base, direction_vec)
    center = (np.array(padded.shape) - 1) / 2
    matrix = R.T
    offset = center - matrix @ center
    rotated = affine_transform(
        padded,
        matrix=matrix,
        offset=offset,
        order=1,
        mode="constant",
        cval=0,
    )
    return rotated.astype(cell.dtype)


def can_place(mask, cell, position):
    cz, cy, cx = position.astype(int)
    dz, dy, dx = cell.shape
    hz, hy, hx = dz // 2, dy // 2, dx // 2

    z0, z1 = max(0, cz - hz), min(mask.shape[0], cz + hz + 1)
    y0, y1 = max(0, cy - hy), min(mask.shape[1], cy + hy + 1)
    x0, x1 = max(0, cx - hx), min(mask.shape[2], cx + hx + 1)

    if z0 >= z1 or y0 >= y1 or x0 >= x1:
        return False

    cell_z0 = hz - (cz - z0)
    cell_y0 = hy - (cy - y0)
    cell_x0 = hx - (cx - x0)

    subcell = cell[
        cell_z0 : cell_z0 + (z1 - z0),
        cell_y0 : cell_y0 + (y1 - y0),
        cell_x0 : cell_x0 + (x1 - x0),
    ]

    return np.all(mask[z0:z1, y0:y1, x0:x1][subcell > 0] == 0)

number_of_cells = 250
max_attempts = 30
radius_X = radius_Y = 12
radius_Z = 5
randomness = 0.2

vol_shape = (300,300,300)
volume = np.zeros(vol_shape, dtype=np.uint16)
mask = np.zeros_like(volume)

organoid_size = 250

viewer = napari.Viewer(ndisplay=3)

for cell_idx in range(number_of_cells):
    # create a binomial distrubution around the radii with the arms reaching the randomness value
    rand_radius_X = int(radius_X + np.random.uniform(-randomness, randomness) * radius_X)
    rand_radius_Y = int(radius_Y + np.random.uniform(-randomness, randomness) * radius_Y)
    rand_radius_Z = int(radius_Z + np.random.uniform(-randomness, randomness) * radius_Z)
    cell = make_cell(rand_radius_Z, rand_radius_Y, rand_radius_X, intensity=255)

    placed = False
    for attempt in range(max_attempts):
        # get a random position at distance of organoid_size/2 from center
        u = np.random.uniform(-1, 1)  # cos(theta)
        phi = np.random.uniform(0, 2 * np.pi)
        theta = np.arccos(u)
        r = organoid_size / 2 # controls how far from center the cells are placed
        pos_z = int(center[0] + r * u)
        sin_theta = np.sqrt(1 - u * u)
        pos_y = int(center[1] + r * sin_theta * np.cos(phi))
        pos_x = int(center[2] + r * sin_theta * np.sin(phi))
        position = np.array([pos_z, pos_y, pos_x])

        # place the cell in the volume at the random position
        direction = center - position  # point toward organoid center
        oriented_cell = orient_cell(cell, direction)

        if not can_place(mask, oriented_cell, position):
            continue

        paste_success = paste_cell(volume, mask, oriented_cell, position, label=cell_idx + 1)
        if paste_success:
            placed = True
            print(
                f"Cell {cell_idx+1}: position=({pos_z}, {pos_y}, {pos_x}), radii=({rand_radius_Z}, {rand_radius_Y}, {rand_radius_X})"
            )
            break

    if not placed:
        print(f"Cell {cell_idx}: skipped after {max_attempts} attempts")

rescale = ((vol_shape[0] / (2.5 / 0.64) / vol_shape[0]), 1.0, 1.0)
volume = zoom(volume, zoom=rescale, order=1)
mask = zoom(mask, zoom=rescale, order=0)
output_directory = r"C:\Users\6331823\Local SSD\Fake_data"
tifffile.imwrite(os.path.join(output_directory, "perfect_organoid.tif"), volume)
tifffile.imwrite(os.path.join(output_directory, "perfect_mask.tif"), mask)

unique_labels = np.unique(mask)
unique_labels = unique_labels[unique_labels > 0]

rng = np.random.default_rng()

brightness_volume = np.zeros_like(volume, dtype=np.float32)

for lbl in unique_labels:
    cell_voxels = mask == lbl
    cell_mean = np.clip(rng.normal(200, 15), 150, 250)
    cell_noise = rng.normal(loc=cell_mean, scale=5, size=cell_voxels.sum())
    lo = max(150, cell_mean - 10)
    hi = min(250, cell_mean + 10)
    brightness_volume[cell_voxels] = np.clip(cell_noise, lo, hi)

brightness_volume = brightness_volume.astype(np.uint16)
tifffile.imwrite(os.path.join(output_directory, "brightness_adjusted_organoid.tif"), brightness_volume)

gaussian_volume = gaussian_filter(
    brightness_volume.astype(np.float32), sigma=(1.6, 0.6, 0.6)
)
tifffile.imwrite(
    os.path.join(output_directory, "gaussian_organoid.tif"),
    gaussian_volume.astype(np.uint16),
)

z_profile = np.linspace(0.9, 0.3, volume.shape[0], dtype=np.float32)[:, None, None]
realistic_volume = gaussian_volume.astype(np.float32) * z_profile
realistic_volume = np.clip(realistic_volume, 0, 255).astype(np.uint16)
tifffile.imwrite(
    os.path.join(output_directory, "realistic_organoid.tif"),
    realistic_volume.astype(np.uint16),
)

scale = (2.5, 0.64, 0.64)
viewer.add_image(volume, name="synthetic_volume", scale=scale)
viewer.add_labels(mask, name="synthetic_mask", scale=scale)
viewer.add_image(brightness_volume, name="brightness_volume", scale=scale)
viewer.add_image(gaussian_volume, name="gaussian_volume", scale=scale)
viewer.add_image(realistic_volume, name="realistic_volume", scale=scale)

Cell 1: position=(47, 201, 198), radii=(4, 10, 10)
Cell 2: position=(150, 104, 33), radii=(4, 10, 11)
Cell 3: position=(45, 198, 101), radii=(5, 13, 9)
Cell 4: position=(226, 148, 51), radii=(4, 9, 14)
Cell 5: position=(146, 57, 65), radii=(4, 10, 10)
Cell 6: position=(34, 149, 196), radii=(5, 11, 11)
Cell 7: position=(158, 247, 227), radii=(5, 13, 13)
Cell 8: position=(92, 70, 227), radii=(4, 12, 11)
Cell 9: position=(106, 235, 230), radii=(4, 11, 9)
Cell 10: position=(222, 48, 150), radii=(5, 12, 13)
Cell 11: position=(211, 50, 195), radii=(5, 12, 10)
Cell 12: position=(186, 42, 98), radii=(4, 10, 10)
Cell 13: position=(84, 235, 213), radii=(5, 14, 11)
Cell 14: position=(71, 128, 245), radii=(4, 10, 10)
Cell 15: position=(156, 44, 216), radii=(4, 13, 10)
Cell 16: position=(267, 178, 117), radii=(4, 10, 14)
Cell 17: position=(192, 256, 99), radii=(4, 10, 13)
Cell 18: position=(217, 190, 247), radii=(4, 12, 12)
Cell 19: position=(177, 120, 268), radii=(5, 11, 11)
Cell 20: position=(158, 268, 189), radii=(4, 10, 12)
Cell 21: position=(272, 139, 172), radii=(4, 10, 11)
Cell 22: position=(215, 61, 89), radii=(5, 10, 13)
Cell 23: position=(257, 181, 94), radii=(4, 11, 11)
Cell 24: position=(259, 175, 204), radii=(5, 10, 14)
Cell 25: position=(235, 208, 220), radii=(5, 13, 9)
Cell 26: position=(66, 186, 64), radii=(4, 10, 13)
Cell 27: position=(244, 85, 201), radii=(4, 12, 12)
Cell 28: position=(140, 110, 268), radii=(4, 11, 13)
Cell 29: position=(160, 253, 80), radii=(4, 12, 13)
Cell 30: position=(181, 88, 254), radii=(5, 10, 12)
Cell 31: position=(102, 151, 265), radii=(5, 13, 10)
Cell 32: position=(215, 226, 75), radii=(5, 9, 13)
Cell 33: position=(124, 185, 33), radii=(4, 13, 11)
Cell 34: position=(205, 79, 62), radii=(5, 10, 10)
Cell 35: position=(111, 199, 258), radii=(4, 12, 12)
Cell 36: position=(140, 267, 109), radii=(4, 12, 13)
Cell 37: position=(177, 271, 163), radii=(5, 12, 10)
Cell 38: position=(201, 215, 243), radii=(5, 14, 13)
Cell 39: position=(256, 87, 169), radii=(4, 12, 12)
Cell 40: position=(56, 222, 110), radii=(5, 14, 10)
Cell 41: position=(124, 265, 191), radii=(5, 12, 13)
Cell 42: position=(111, 81, 247), radii=(4, 13, 11)
Cell 43: position=(138, 228, 246), radii=(4, 11, 13)
Cell 44: position=(170, 66, 58), radii=(4, 11, 10)
Cell 45: position=(128, 255, 212), radii=(4, 12, 9)
Cell 46: position=(41, 149, 87), radii=(5, 12, 14)
Cell 47: position=(72, 245, 172), radii=(4, 13, 10)
Cell 48: position=(156, 33, 195), radii=(4, 12, 11)
Cell 49: position=(70, 212, 76), radii=(4, 12, 11)
Cell 50: position=(185, 49, 214), radii=(4, 11, 14)
Cell 51: position=(80, 162, 253), radii=(5, 10, 9)
Cell 52: position=(188, 158, 268), radii=(4, 9, 12)
Cell 53: position=(238, 192, 73), radii=(5, 10, 10)
Cell 54: position=(98, 240, 81), radii=(4, 12, 11)
Cell 55: position=(119, 47, 84), radii=(4, 10, 9)
Cell 56: position=(98, 258, 113), radii=(4, 12, 10)
Cell 57: position=(89, 220, 233), radii=(5, 10, 13)
Cell 58: position=(29, 178, 132), radii=(5, 14, 13)
Cell 59: position=(27, 167, 169), radii=(4, 12, 10)
Cell 60: position=(175, 87, 44), radii=(5, 13, 13)
Cell 61: position=(120, 29, 135), radii=(4, 13, 10)
Cell 62: position=(45, 95, 108), radii=(5, 10, 9)
Cell 63: position=(113, 126, 32), radii=(4, 11, 10)
Cell 64: position=(86, 195, 52), radii=(4, 12, 11)
Cell 65: position=(208, 188, 46), radii=(4, 12, 13)
Cell 66: position=(87, 42, 157), radii=(5, 12, 12)
Cell 67: position=(143, 230, 54), radii=(5, 14, 10)
Cell 68: position=(34, 111, 123), radii=(5, 11, 13)
Cell 69: position=(206, 252, 194), radii=(4, 10, 10)
Cell 70: position=(104, 68, 67), radii=(5, 12, 11)
Cell 71: position=(224, 250, 148), radii=(4, 12, 13)
Cell 72: position=(243, 232, 141), radii=(4, 13, 11)
Cell 73: position=(52, 102, 212), radii=(4, 11, 13)
Cell 74: position=(35, 199, 155), radii=(4, 11, 10)
Cell 75: position=(47, 88, 185), radii=(4, 11, 14)
Cell 76: position=(260, 115, 103), radii=(4, 14, 13)
Cell 77: position=(68, 74, 207), radii=(4, 12, 12)
Cell 78: position=(228, 165, 245), radii=(4, 12, 13)
Cell 79: position=(244, 141, 231), radii=(5, 12, 10)
Cell 80: position=(45, 162, 217), radii=(5, 13, 10)
Cell 81: position=(148, 25, 165), radii=(5, 9, 12)
Cell 82: position=(224, 95, 65), radii=(4, 13, 12)
Cell 83: position=(234, 120, 62), radii=(5, 13, 13)
Cell 84: position=(242, 232, 165), radii=(5, 12, 12)
Cell 85: position=(151, 274, 155), radii=(4, 10, 13)
Cell 86: position=(183, 33, 120), radii=(5, 12, 10)
Cell 87: position=(258, 200, 187), radii=(5, 10, 13)
Cell 88: position=(268, 189, 142), radii=(4, 12, 14)
Cell 89: position=(93, 260, 138), radii=(5, 10, 13)
Cell 90: position=(187, 69, 237), radii=(4, 13, 11)
Cell 91: position=(179, 185, 33), radii=(5, 11, 13)
Cell 92: position=(102, 38, 182), radii=(4, 10, 11)
Cell 93: position=(97, 111, 43), radii=(4, 9, 9)
Cell 94: position=(60, 62, 150), radii=(4, 13, 13)
Cell 95: position=(27, 138, 171), radii=(5, 12, 12)
Cell 96: position=(184, 117, 34), radii=(4, 10, 12)
Cell 97: position=(225, 96, 234), radii=(4, 14, 9)
Cell 98: position=(138, 72, 52), radii=(5, 9, 13)
Cell 99: position=(149, 32, 107), radii=(4, 13, 12)
Cell 100: position=(74, 107, 59), radii=(5, 10, 13)
Cell 101: position=(206, 144, 38), radii=(4, 9, 9)
Cell 102: position=(241, 75, 109), radii=(4, 11, 11)
Cell 103: position=(243, 217, 101), radii=(4, 13, 11)
Cell 104: position=(267, 147, 192), radii=(5, 10, 11)
Cell 105: position=(57, 232, 134), radii=(5, 11, 12)
Cell 106: position=(109, 206, 46), radii=(4, 10, 11)
Cell 107: position=(52, 140, 228), radii=(5, 10, 11)
Cell 108: position=(34, 184, 183), radii=(5, 12, 9)
Cell 109: position=(193, 265, 127), radii=(4, 14, 11)
Cell 110: position=(242, 187, 225), radii=(4, 12, 10)
Cell 111: position=(195, 33, 152), radii=(5, 13, 12)
Cell 112: position=(51, 107, 85), radii=(5, 13, 12)
Cell 113: position=(116, 54, 223), radii=(5, 9, 14)
Cell 114: position=(179, 31, 177), radii=(4, 11, 12)
Cell 115: position=(26, 136, 132), radii=(5, 13, 11)
Cell 116: position=(40, 204, 126), radii=(5, 10, 13)
Cell 117: position=(93, 54, 207), radii=(4, 10, 11)
Cell 118: position=(202, 238, 220), radii=(5, 10, 10)
Cell 119: position=(78, 71, 84), radii=(5, 10, 12)
Cell 120: position=(220, 133, 252), radii=(5, 13, 11)
Cell 121: position=(67, 142, 56), radii=(5, 11, 13)
Cell 122: position=(271, 167, 170), radii=(4, 10, 13)
Cell 123: position=(137, 154, 25), radii=(4, 11, 12)
Cell 124: position=(159, 218, 45), radii=(5, 12, 11)
Cell 125: position=(259, 92, 129), radii=(4, 12, 12)
Cell 126: position=(77, 242, 107), radii=(4, 11, 11)
Cell 127: position=(162, 271, 123), radii=(4, 13, 10)
Cell 128: position=(137, 192, 266), radii=(5, 11, 11)
Cell 129: position=(89, 157, 40), radii=(5, 11, 11)
Cell 130: position=(52, 75, 126), radii=(4, 12, 10)
Cell 131: position=(144, 61, 237), radii=(4, 13, 11)
Cell 132: position=(189, 243, 77), radii=(5, 11, 11)
Cell 133: position=(43, 208, 177), radii=(4, 12, 12)
Cell 134: position=(113, 115, 264), radii=(5, 14, 9)
Cell 135: position=(71, 194, 236), radii=(5, 13, 11)
Cell 136: position=(269, 121, 129), radii=(5, 12, 10)
Cell 137: position=(66, 212, 218), radii=(5, 13, 12)
Cell 138: position=(208, 43, 120), radii=(4, 13, 13)
Cell 139: position=(243, 95, 87), radii=(4, 12, 12)
Cell 140: position=(163, 136, 26), radii=(4, 10, 13)
Cell 140: skipped after 30 attempts
Cell 142: position=(167, 44, 85), radii=(4, 10, 13)
Cell 143: position=(225, 53, 175), radii=(4, 11, 10)
Cell 144: position=(177, 230, 241), radii=(4, 10, 11)
Cell 145: position=(188, 188, 262), radii=(5, 12, 13)
Cell 146: position=(40, 89, 145), radii=(5, 11, 12)
Cell 147: position=(123, 255, 87), radii=(4, 11, 13)
Cell 148: position=(266, 111, 172), radii=(5, 10, 12)
Cell 148: skipped after 30 attempts
Cell 150: position=(95, 220, 62), radii=(5, 13, 13)
Cell 151: position=(265, 143, 103), radii=(5, 13, 11)
Cell 151: skipped after 30 attempts
Cell 153: position=(95, 179, 258), radii=(4, 9, 12)
Cell 154: position=(251, 133, 79), radii=(4, 9, 12)
Cell 154: skipped after 30 attempts
Cell 156: position=(194, 57, 77), radii=(5, 11, 12)
Cell 157: position=(31, 109, 148), radii=(5, 10, 11)
Cell 157: skipped after 30 attempts
Cell 159: position=(205, 110, 45), radii=(4, 13, 10)
Cell 160: position=(189, 161, 32), radii=(4, 11, 10)
Cell 161: position=(150, 184, 29), radii=(4, 12, 13)
Cell 162: position=(225, 239, 107), radii=(4, 9, 12)
Cell 163: position=(144, 168, 273), radii=(4, 13, 11)
Cell 164: position=(163, 26, 134), radii=(5, 14, 12)
Cell 165: position=(200, 264, 153), radii=(4, 13, 10)
Cell 166: position=(37, 115, 191), radii=(5, 13, 10)
Cell 167: position=(153, 136, 274), radii=(4, 12, 14)
Cell 168: position=(109, 267, 164), radii=(4, 9, 13)
Cell 169: position=(29, 154, 117), radii=(4, 11, 10)
Cell 170: position=(249, 165, 76), radii=(4, 10, 13)
Cell 171: position=(100, 255, 196), radii=(4, 11, 13)
Cell 172: position=(122, 94, 41), radii=(4, 10, 10)
Cell 173: position=(66, 62, 181), radii=(5, 11, 10)
Cell 174: position=(166, 166, 27), radii=(5, 9, 10)
Cell 175: position=(80, 104, 243), radii=(4, 9, 11)
Cell 175: skipped after 30 attempts
Cell 176: skipped after 30 attempts
Cell 177: skipped after 30 attempts
Cell 179: position=(96, 87, 55), radii=(5, 11, 12)
Cell 179: skipped after 30 attempts
Cell 181: position=(161, 188, 268), radii=(4, 10, 10)
Cell 182: position=(232, 173, 58), radii=(5, 13, 12)
Cell 183: position=(65, 229, 196), radii=(5, 13, 11)
Cell 184: position=(122, 162, 271), radii=(5, 10, 9)
Cell 185: position=(146, 87, 258), radii=(5, 14, 10)
Cell 185: skipped after 30 attempts
Cell 187: position=(274, 157, 136), radii=(4, 10, 12)
Cell 188: position=(257, 208, 122), radii=(5, 10, 13)
Cell 189: position=(191, 211, 49), radii=(4, 12, 11)
Cell 190: position=(32, 111, 170), radii=(5, 9, 10)
Cell 190: skipped after 30 attempts
Cell 192: position=(82, 50, 115), radii=(5, 10, 12)
Cell 192: skipped after 30 attempts
Cell 194: position=(225, 72, 212), radii=(4, 9, 12)
Cell 194: skipped after 30 attempts
Cell 196: position=(125, 241, 68), radii=(4, 9, 9)
Cell 196: skipped after 30 attempts
Cell 198: position=(113, 36, 112), radii=(5, 10, 12)
Cell 199: position=(233, 59, 126), radii=(5, 13, 11)
Cell 199: skipped after 30 attempts
Cell 201: position=(124, 270, 129), radii=(4, 12, 9)
Cell 201: skipped after 30 attempts
Cell 203: position=(257, 118, 205), radii=(5, 14, 10)
Cell 204: position=(98, 37, 131), radii=(4, 9, 11)
Cell 204: skipped after 30 attempts
Cell 205: skipped after 30 attempts
Cell 206: skipped after 30 attempts
Cell 208: position=(46, 177, 85), radii=(5, 10, 14)
Cell 208: skipped after 30 attempts
Cell 209: skipped after 30 attempts
Cell 210: skipped after 30 attempts
Cell 212: position=(258, 212, 157), radii=(5, 13, 9)
Cell 212: skipped after 30 attempts
Cell 213: skipped after 30 attempts
Cell 214: skipped after 30 attempts
Cell 216: position=(239, 221, 200), radii=(5, 9, 10)
Cell 216: skipped after 30 attempts
Cell 217: skipped after 30 attempts
Cell 218: skipped after 30 attempts
Cell 220: position=(123, 29, 170), radii=(5, 10, 12)
Cell 221: position=(175, 211, 255), radii=(5, 11, 13)
Cell 221: skipped after 30 attempts
Cell 223: position=(200, 124, 261), radii=(4, 9, 11)
Cell 224: position=(49, 224, 157), radii=(4, 11, 12)
Cell 224: skipped after 30 attempts
Cell 226: position=(240, 64, 160), radii=(4, 11, 9)
Cell 226: skipped after 30 attempts
Cell 227: skipped after 30 attempts
Cell 228: skipped after 30 attempts
Cell 229: skipped after 30 attempts
Cell 230: skipped after 30 attempts
Cell 231: skipped after 30 attempts
Cell 232: skipped after 30 attempts
Cell 233: skipped after 30 attempts
Cell 234: skipped after 30 attempts
Cell 236: position=(184, 258, 201), radii=(4, 10, 13)
Cell 237: position=(137, 125, 27), radii=(5, 12, 11)
Cell 238: position=(96, 53, 92), radii=(4, 11, 12)
Cell 238: skipped after 30 attempts
Cell 239: skipped after 30 attempts
Cell 241: position=(205, 102, 251), radii=(5, 12, 10)
Cell 241: skipped after 30 attempts
Cell 242: skipped after 30 attempts
Cell 243: skipped after 30 attempts
Cell 244: skipped after 30 attempts
Cell 245: skipped after 30 attempts
Cell 246: skipped after 30 attempts
Cell 247: skipped after 30 attempts
Cell 248: skipped after 30 attempts
Cell 249: skipped after 30 attempts

In [103]:
from scipy.ndimage import gaussian_filter, map_coordinates

# axial elongation / blur
brightness_volume = tifffile.imread(os.path.join(output_directory, "brightness_adjusted_organoid.tif"))


scale = (2.5, 0.64, 0.64)
viewer = napari.Viewer(ndisplay=3)
viewer.add_image(brightness_volume, name="synthetic_volume", scale=scale)
viewer.add_labels(mask, name="synthetic_mask", scale=scale)
viewer.add_image(brightness_volume, name="brightness_volume", scale=scale)

In [102]:
gaussian_volume = gaussian_filter(
    brightness_volume.astype(np.float32), sigma=(3, 0.6, 0.6)
)
z_profile = np.linspace(0.9, 0.3, volume.shape[0], dtype=np.float32)[:, None, None]
realistic_volume = gaussian_volume.astype(np.float32) * z_profile
realistic_volume = np.clip(realistic_volume, 0, 255).astype(np.uint16)
viewer = napari.Viewer(ndisplay=3)
scale = (2.5, 0.64, 0.64)
viewer.add_image(volume, name="synthetic_volume", scale=scale)
viewer.add_labels(mask, name="synthetic_mask", scale=scale)
viewer.add_image(brightness_volume, name="brightness_volume", scale=scale)
viewer.add_image(gaussian_volume, name="gaussian_volume", scale=scale)
viewer.add_image(realistic_volume, name="realistic_volume", scale=scale)

AttributeError: 'list' object has no attribute 'shape'

Cleaner version of organoid stitcher

In [31]:
import tifffile
import pandas as pd
from skimage.measure import regionprops, regionprops_table
import napari
import numpy as np
import os
from dataclasses import dataclass
import scipy.spatial


@dataclass
class cell_3d:
    label: int
    centroid: tuple
    coords_set: set
    volume: int
    labels_2d: list | None = None
    centroids_2d: list | None = None
    coords_set_2d: list | None = None
    volumes_2d: list | None = None
    # per-slice per-channel intensities, dict of lists keyed by channel name
    intensities_2d: dict | None = None
    # aggregated per-channel intensities (mean across slices), keys like "intensity_wt"
    intensities: dict | None = None
    break_scores: list | None = None
    parents: list | None = None
    touching_cells: list | None = None


@dataclass
class cell_2d:
    label: int
    centroid: tuple
    coords_set: set
    volume: int

    def __post_init__(self):
        self._intensities = {}


def get_cell_properties_2d(image):
    # Get the properties of every mask in the image
    props = regionprops(image)

    organoid = []

    # For every mask found, get the label, centeroid, boundingbox, and volume
    for prop in props:
        # Pre-compute coordinate set for fast IOU calculations later
        coords_2d = prop.coords[:, 1:]
        coords_set = set(map(tuple, coords_2d))

        cell = cell_2d(
            label=prop.label,
            centroid=prop.centroid,  # (z, y, x)
            coords_set=coords_set,
            volume=prop.area,
        )
        organoid.append(cell)

    return organoid


def properties_channel(organoid, mask, image, channel_type=None):
    props_channel = regionprops_table(
        mask, intensity_image=image, properties=["label", "mean_intensity"]
    )
    intensity_dict = dict(zip(props_channel["label"], props_channel["mean_intensity"]))

    for cell in organoid:
        attr_name = f"intensity_{channel_type}" if channel_type else "intensity"
        setattr(cell, attr_name, intensity_dict.get(cell.label, 0))

    return organoid


def make_unique_mask(mask):
    """Makes a fresh mask from a already stitched mask"""
    unique_mask = []
    number = 1
    for z in range(mask.shape[0]):
        # go over every unique number in the mask and create a new slice with a new unique number 1 higher
        slice = mask[z]
        unique_slice = mask[z].copy()
        for val in range(1, slice.max() + 1):
            unique_slice[slice == val] = number
            number += 1
        unique_mask.append(unique_slice)
    unique_mask = np.stack(unique_mask, axis=0)

    return unique_mask

def get_2d_mask_properties(mask, image1, image_type_1=None, image2=None, image_type_2=None):
    unique_mask = make_unique_mask(mask)
    organoid = get_cell_properties_2d(unique_mask)

    organoid = properties_channel(organoid, unique_mask, image1, channel_type=image_type_1)

    if image2 is not None:
        organoid = properties_channel(
            organoid, unique_mask, image2, channel_type=image_type_2
        )

    return organoid


def calculate_iou(coords_sets, idx1, idx2):
    """
    Calculate overlap metric for cell matching.
    Returns 1 if the smaller cell is completely contained in the larger cell.
    Otherwise returns intersection over union (standard IOU).
    """
    set1 = coords_sets[idx1]
    set2 = coords_sets[idx2]

    # Check if either set is empty
    len1, len2 = len(set1), len(set2)
    if len2 == 0:
        return 0

    # Calculate intersection (overlapping pixels)
    intersection = len(set1 & set2)

    if intersection == 0:
        return 0  # No overlap = different cells

    # If the smaller cell is completely contained in the larger cell, return 1
    min_len = min(len1, len2)
    if intersection == min_len:
        return 1.0  # One cell completely covers the other

    # Otherwise, use standard IOU
    union = len1 + len2 - intersection
    return intersection / union


def IOU_stitching(organoid_2d, distance_threshold=10, iou_threshold=0.3):
    print("Starting IOU based 3D stitching...")
    n = len(organoid_2d)
    z_array = np.array([c.centroid[0] for c in organoid_2d])
    y_array = np.array([c.centroid[1] for c in organoid_2d])
    x_array = np.array([c.centroid[2] for c in organoid_2d])
    coords_sets = {i: c.coords_set for i, c in enumerate(organoid_2d)}

    # group by integer z to increase speed
    z_groups = {}
    for idx, z_val in enumerate(z_array):
        z_int = int(round(z_val))
        z_groups.setdefault(z_int, []).append(idx)

    labels_3d = np.full(n, -1, dtype=np.int32)

    def stitch_forward(idx, current_label):
        labels_3d[idx] = current_label
        next_z = int(round(z_array[idx])) + 1
        if next_z not in z_groups:
            return
        # get all cells that havent been stitched yet
        candidates = [c for c in z_groups[next_z] if labels_3d[c] == -1] 
        if not candidates:
            return
        cand_arr = np.array(candidates)
        dists = np.hypot(
            x_array[cand_arr] - x_array[idx], y_array[cand_arr] - y_array[idx]
        )
        closest_cell = np.argmin(dists)
        if dists[closest_cell] > distance_threshold:
            return
        cand_idx = cand_arr[closest_cell]
        if calculate_iou(coords_sets, idx, cand_idx) > iou_threshold:
            stitch_forward(cand_idx, current_label)

    current_label = 0
    for i in range(n):
        if labels_3d[i] == -1:
            current_label += 1
            stitch_forward(i, current_label)

    # build organoid_3d list
    organoid_3d = []
    intensity_attrs = [a for a in organoid_2d[0].__dict__ if a.startswith("intensity")]
    for cell in np.unique(labels_3d):
        if cell <= 0:
            continue
        slice_idxs = np.where(labels_3d == cell)[0]
        labels_2d = [organoid_2d[i].label for i in slice_idxs]
        centroids_2d = [organoid_2d[i].centroid for i in slice_idxs]
        coords_set_2d = [organoid_2d[i].coords_set for i in slice_idxs]
        volumes_2d = [organoid_2d[i].volume for i in slice_idxs]
        # collect per-channel per-slice intensities
        intensities_2d = {
            attr: [getattr(organoid_2d[i], attr, None) for i in slice_idxs]
            for attr in intensity_attrs
        }

        coords_3d = set()
        for z_idx, (z, _, _) in enumerate(centroids_2d):
            z_int = int(round(z))
            for y, x in coords_set_2d[z_idx]:
                coords_3d.add((z_int, int(y), int(x)))

        cell3d = cell_3d(
            label=cell,
            centroid=np.mean(centroids_2d, axis=0),
            coords_set=coords_3d,
            volume=sum(volumes_2d),
            labels_2d=labels_2d,
            centroids_2d=centroids_2d,
            coords_set_2d=coords_set_2d,
            volumes_2d=volumes_2d,
            intensities_2d=intensities_2d,
        )
        organoid_3d.append(cell3d)

    print(f"Completed IOU based stitching: {len(organoid_3d)} cells formed.")

    return organoid_3d

def mask_from_organoid(organoid, shape):
    mask = np.zeros(shape, dtype=np.uint16)
    for cell in organoid:
        for z_idx, (z, y, x) in enumerate(cell.centroids_2d):
            z_int = int(round(z))
            if 0 <= z_int < shape[0]:
                for yy, xx in cell.coords_set_2d[z_idx]:
                    if 0 <= yy < shape[1] and 0 <= xx < shape[2]:
                        mask[z_int, yy, xx] = cell.label
    return mask


def break_score(values, i):
    # Calculate intensity-based anomalies by getting a score that resembles high-low-high intensity value patterns
    # Calculate ratio between slice i and below i, and i and above i
    values_bottom = max(values[:i])
    values_top = max(values[i + 1 :])
    ratio_1 = values_bottom / values[i]
    ratio_2 = values[i] / values_top

    # divide this again, now high low high gets higher score then other patterns
    return ratio_1 / ratio_2

def get_centroid_positions(centroid):
    z_positions = [c[0] for c in centroid]
    y_positions = [c[1] for c in centroid]
    x_positions = [c[2] for c in centroid]
    return z_positions, y_positions, x_positions


def calculate_line_3d(z_positions, y_positions, x_positions, points=3):
    # Fit line to specified points (int, tuple, or slice)
    if isinstance(points, tuple):
        points = slice(*points)
    elif isinstance(points, int):
        points = slice(None, points)

    z_fit = np.array(z_positions[points])
    x_fit = np.array(x_positions[points])
    y_fit = np.array(y_positions[points])

    # Calculate line parameters
    A = np.vstack([z_fit, np.ones(len(z_fit))]).T
    m_x, c_x = np.linalg.lstsq(A, x_fit, rcond=None)[0]
    m_y, c_y = np.linalg.lstsq(A, y_fit, rcond=None)[0]

    # Create line function: given z, returns (x, y) in that order
    line_function = lambda z: (m_x * z + c_x, m_y * z + c_y)

    return line_function


def calculate_point_line_distances(
    z_positions, y_positions, x_positions, line_function
):
    distances = []
    for z, x, y in zip(z_positions, x_positions, y_positions):
        line_x, line_y = line_function(z)
        dist = np.sqrt((x - line_x) ** 2 + (y - line_y) ** 2)
        distances.append(dist)
    return distances

def get_slope_changes(distances):
    # Calculate slope changes in the distance array
    slopes = np.diff(distances)
    slope_changes = np.diff(slopes)

    # Pad to match original length
    slope_changes = np.concatenate([[0], slope_changes, [0]])
    return slope_changes

def get_volume_break_scores(cell):
    num_slices = len(cell.volumes_2d)
    volumes_break_score = [0] * num_slices

    for i in range(1, num_slices - 1):
        volumes_break_score[i] = break_score(cell.volumes_2d, i)

    return volumes_break_score

def get_intensity_break_scores(cell):
    num_slices = len(cell.volumes_2d)
    intensity_break_score = [0] * num_slices

    if cell.intensities_2d:
        per_channel = list(cell.intensities_2d.values())
        max_intensity = [max(vals) for vals in zip(*per_channel)]
    else:
        max_intensity = [0] * num_slices

    for i in range(1, num_slices - 1):
        intensity_break_score[i] = break_score(max_intensity, i)

    return intensity_break_score

def get_line_break_scores(z_positions, y_positions, x_positions):
    # Calculate line-based break scores (from bottom_up)
    line = calculate_line_3d(z_positions, y_positions, x_positions, points=3)
    distances = calculate_point_line_distances(z_positions, y_positions, x_positions, line)
    break_score = abs(get_slope_changes(distances))
    return break_score

def get_IOU_break_scores(cell):
    num_slices = len(cell.volumes_2d)
    iou_break_score = [0] * num_slices

    for i in range(1, num_slices - 1):
        iou_break_score[i] = 1 - calculate_iou(
            cell.coords_set_2d, i - 1, i
        )

    return iou_break_score

def get_break_scores(organoid):
    for cell in organoid:
        num_slices = len(cell.volumes_2d)
        if num_slices < 5:
            cell.break_scores = [0] * num_slices
            continue

        # Calculate volume-based break scores
        volumes_break_score = get_volume_break_scores(cell)
        # Calculate intensity-based break scores
        intensity_break_score = get_intensity_break_scores(cell)

        # Calculate line-based break scores (from bottom_up)
        z_positions, y_positions, x_positions = get_centroid_positions(cell.centroids_2d)
        break_score_up = get_line_break_scores(z_positions, y_positions, x_positions)
        # pad 1 at start and remove last to match and better represent breaks between slices
        break_score_up = np.concatenate([[0], break_score_up[:-1]])
        # Calculate line-based break scores (from top_down)
        break_score_down = get_line_break_scores(
            z_positions[::-1], y_positions[::-1], x_positions[::-1]
        )[::-1]
        IOU_break_score = get_IOU_break_scores(cell)

        # Calculate final break scores
        final_scores = []
        for v_score, i_score, up_score, down_score, IOU_score in zip(
            volumes_break_score,
            intensity_break_score,
            break_score_up,
            break_score_down,
            IOU_break_score,
        ):
            final_score = np.max([up_score, down_score]) * v_score * (i_score**2) * (IOU_score*2)
            # if cell.label == 83:
            #     print(f"v:{v_score:.2f}, i:{i_score:.2f}, up:{up_score:.2f}, down:{down_score:.2f}, IOU:{IOU_score:.2f}, final:{final_score:.2f}")
            final_scores.append(final_score)

        cell.break_scores = final_scores

    return organoid

def split_cell_at_index(cell, break_position, new_label):
    # Build parent lineage: existing parents + current label
    parent_lineage = (cell.parents or []) + [cell.label]

    # Build 3D coords_set for bottom cell
    coords_3d_bottom = set()
    for z_idx in range(break_position):
        z_int = int(round(cell.centroids_2d[z_idx][0]))
        for y, x in cell.coords_set_2d[z_idx]:
            coords_3d_bottom.add((z_int, int(y), int(x)))

    bottom_cell = cell_3d(
        label=cell.label,
        centroid=np.mean(cell.centroids_2d[:break_position], axis=0),
        coords_set=coords_3d_bottom,
        volume=sum(cell.volumes_2d[:break_position]),
        labels_2d=cell.labels_2d[:break_position],
        centroids_2d=cell.centroids_2d[:break_position],
        coords_set_2d=cell.coords_set_2d[:break_position],
        volumes_2d=cell.volumes_2d[:break_position],
        intensities_2d={
            k: v[:break_position] for k, v in (cell.intensities_2d or {}).items()
        },
        parents=parent_lineage,
    )

    # Build 3D coords_set for top cell
    max_z = len(cell.volumes_2d)
    coords_3d_top = set()
    for z_idx in range(break_position, max_z):
        z_int = int(round(cell.centroids_2d[z_idx][0]))
        for y, x in cell.coords_set_2d[z_idx]:
            coords_3d_top.add((z_int, int(y), int(x)))

    top_cell = cell_3d(
        label=new_label,
        centroid=np.mean(cell.centroids_2d[break_position:max_z], axis=0),
        coords_set=coords_3d_top,
        volume=sum(cell.volumes_2d[break_position:max_z]),
        labels_2d=cell.labels_2d[break_position:max_z],
        centroids_2d=cell.centroids_2d[break_position:max_z],
        coords_set_2d=cell.coords_set_2d[break_position:max_z],
        volumes_2d=cell.volumes_2d[break_position:max_z],
        intensities_2d={
            k: v[break_position:max_z] for k, v in (cell.intensities_2d or {}).items()
        },
        parents=parent_lineage,
    )

    return bottom_cell, top_cell

def break_stitching(organoid, breaking_threshold = 2.5):
    new_organoid = []
    breaks_made = 0
    new_label = max(cell.label for cell in organoid) + 1
    for cell in organoid:
        if len(cell.volumes_2d) < 7:
            new_organoid.append(cell)
            continue
        # if cell.label == 103:
        #     print(cell.break_scores)
        # Find indices where break score exceeds threshold
        break_scores = [score for score in cell.break_scores]
        break_scores[:3] = [0, 0, 0]  # First 3 slices get score 0
        break_scores[-3:] = [0, 0, 0]  # Last 3 slices get score 0
        if max(break_scores) < breaking_threshold:
            new_organoid.append(cell)
            continue

        # break indice is the highest scoring indices above threshold
        max_break_value = max(break_scores)
        break_position = break_scores.index(max_break_value)

        # Create new cells by breaking at the identified indices
        bottom_cell, top_cell = split_cell_at_index(cell, break_position, new_label=new_label)
        new_organoid.append(bottom_cell)
        new_organoid.append(top_cell)
        new_label += 1
        breaks_made += 1
    return new_organoid, breaks_made


def find_touching_pairs(organoid):
    neighbor_offsets = [(-1, 0, 0), (1, 0, 0)]  # Only z-direction neighbors

    # Build spatial index using KDTree for fast nearest neighbor search
    centroids = np.array([cell.centroid for cell in organoid])
    tree = scipy.spatial.cKDTree(centroids)

    for i, cell in enumerate(organoid):
        if len(cell.volumes_2d) <= 1:
            cell.touching_cells = []
            continue

        # Query k=10 nearest neighbors (increase if needed, but 5-10 is usually enough)
        distances, indices = tree.query(cell.centroid, k=min(5, len(organoid)))

        # Skip self (first result is always self)
        candidate_indices = indices[1:]

        # Check only nearby candidates for actual touching
        touching_cells = []
        current_boundary = cell.coords_set

        for idx in candidate_indices:
            other_cell = organoid[idx]
            other_coords = other_cell.coords_set

            # Fast boundary check using set operations
            # Create neighbor coordinates for current cell
            neighbor_coords = {
                (z + dz, y, x)
                for z, y, x in current_boundary
                for dz, _, _ in neighbor_offsets
            }

            # Check if any neighbors overlap with other cell
            if neighbor_coords & other_coords:  # Set intersection
                touching_cells.append(other_cell.label)

                # Early exit if we found enough touching cells
                if len(touching_cells) >= 5:
                    break

        cell.touching_cells = touching_cells

    return organoid


def find_touching_cells(organoid):
    # return a list of unique pairs of touching cells
    touching_pairs = set()
    for cell in organoid:
        for touching_label in cell.touching_cells:
            pair = tuple(sorted((cell.label, touching_label)))
            touching_pairs.add(pair)

    return list(touching_pairs)


def calculate_split_coords(cell, index, pred_point_1, pred_point_2):
    # Create splitting line perpendicular to the line between the two predicted points
    # Direction vector between predicted points
    direction = pred_point_2 - pred_point_1
    # Perpendicular vector (rotate 90 degrees)
    normal = direction / (np.linalg.norm(direction) + 1e-8)
    # Midpoint between predicted points
    midpoint = (pred_point_1 + pred_point_2) / 2

    part_1_coords = []
    part_2_coords = []

    for coord in cell.coords_set_2d[index]:
        y, x = coord
        point = np.array([y, x])
        # Vector from midpoint to this point
        to_point = point - midpoint
        # Dot product determines which side of the line
        side = np.dot(to_point, normal)

        if side <= 0:
            part_1_coords.append(coord)
        else:
            part_2_coords.append(coord)

    # Calculate new centroids
    part_1_coords = np.array(part_1_coords)
    part_2_coords = np.array(part_2_coords)

    return part_1_coords, part_2_coords


def are_split_cells_valid(cell, index, part_1_coords, part_2_coords):
    min_size = max(
        3, len(cell.coords_set_2d[index]) * 0.1
    )  # At least 10% of pixels or 3 pixels

    if len(part_1_coords) < min_size or len(part_2_coords) < min_size:
        # print(
        #     f"  Warning: Split too unbalanced ({len(part_1_coords)} vs {len(part_2_coords)} pixels)"
        # )
        return False
    return True


def calculate_new_distances(part_1_coords, part_2_coords, pred_point_1, pred_point_2):
    centroid_1 = np.mean(part_1_coords, axis=0)  # (y, x)
    centroid_2 = np.mean(part_2_coords, axis=0)  # (y, x)

    # Calculate distances from new centroids to predicted points
    dist_c1_to_pred1 = np.sqrt(
        (centroid_1[0] - pred_point_1[0]) ** 2 + (centroid_1[1] - pred_point_1[1]) ** 2
    )
    dist_c2_to_pred2 = np.sqrt(
        (centroid_2[0] - pred_point_2[0]) ** 2 + (centroid_2[1] - pred_point_2[1]) ** 2
    )
    # Check if splitting improves the fit
    avg_new_distance = (dist_c1_to_pred1 + dist_c2_to_pred2) / 2

    return avg_new_distance


def check_split_cells(cell, index, pred_point_1, pred_point_2):
    # centroids_2d stores (z, y, x), so extract y, x
    original_centroid = cell.centroids_2d[index]
    original_y = original_centroid[1]  # y is at index 1
    original_x = original_centroid[2]  # x is at index 2

    original_distance = np.sqrt(
        (original_y - pred_point_1[0]) ** 2 + (original_x - pred_point_1[1]) ** 2
    )

    part_1_coords, part_2_coords = calculate_split_coords(
        cell, index, pred_point_1, pred_point_2
    )


    if not are_split_cells_valid(cell, index, part_1_coords, part_2_coords):
        # print(f"    ✗ Split cells not valid")
        return None

    avg_new_distance = calculate_new_distances(
        part_1_coords, part_2_coords, pred_point_1, pred_point_2
    )

    if avg_new_distance < original_distance:
        # print(
        #     f"    ✓ Splitting improves fit! cell {cell.label} (reduction: {original_distance - avg_new_distance:.2f})"
        # )
        return (part_1_coords, part_2_coords)
    else:
        # print(f"    ✗ Splitting does not improve fit: increase of {avg_new_distance:.2f} >= {original_distance:.2f}")
        return None


def split_multiple_cell_layers(cell_1, cell_2):
    z_to_predicts = [1, 2]
    split_cells = 0
    for z_to_predict in z_to_predicts:
        # Split cell_1 at its top
        # print("bottom cell z:", z_to_predict)
        split_results = split_single_cell_layer(
            cell_1, cell_2, z_to_predict=z_to_predict, bottom_up=True
        )
        if split_results is not None:
            split_cells += 1
            part_1_coords, part_2_coords, z_idx, last_z = split_results
            part_1_coords_2d = set(map(tuple, part_1_coords))
            part_2_coords_2d = set(map(tuple, part_2_coords))
            update_coords(
                cell_1, cell_2, z_idx, part_1_coords_2d, part_2_coords_2d, last_z
            )

        # print("top cell z:", z_to_predict)
        # Split cell_2 at its bottom
        split_results = split_single_cell_layer(
            cell_2, cell_1, z_to_predict=z_to_predict, bottom_up=False
        )
        if split_results is not None:
            split_cells += 1
            part_1_coords, part_2_coords, z_idx, first_z = split_results
            part_1_coords_2d = set(map(tuple, part_1_coords))
            part_2_coords_2d = set(map(tuple, part_2_coords))
            update_coords_bottom(
                cell_2, cell_1, z_idx, part_1_coords_2d, part_2_coords_2d, first_z
            )
        
        # When no splits are made on the 1st level, we dont need to check splitting the second level.
        if split_cells == 0:
            break
    return split_cells


def split_single_cell_layer(cell_1, cell_2, z_to_predict=1, bottom_up=True):
    """
    Split a cell layer at the touching interface.
    bottom_up=True: split cell_1 at its top (for cell_1 splitting cell_2 from above)
    bottum_up=False: split cell_1 at its bottom (for cell_1 splitting from below)
    """
    if len(cell_1.volumes_2d) <= 2 or len(cell_2.volumes_2d) <= 2:
        return None

    z_positions_1, y_positions_1, x_positions_1 = get_centroid_positions(
        cell_1.centroids_2d
    )
    z_positions_2, y_positions_2, x_positions_2 = get_centroid_positions(
        cell_2.centroids_2d
    )

    # Get line fits
    if bottom_up:
        line_1 = calculate_line_3d(
            z_positions_1, y_positions_1, x_positions_1, points=(0, -z_to_predict)
        )
        line_2 = calculate_line_3d(
            z_positions_2[::-1],
            y_positions_2[::-1],
            x_positions_2[::-1],
            points=(0, -z_to_predict),
        )
        z_idx = len(cell_1.volumes_2d) - z_to_predict
        target_z = z_positions_1[-z_to_predict]
    else:
        line_1 = calculate_line_3d(
            z_positions_1[::-1], y_positions_1[::-1], x_positions_1[::-1], points=(0, -z_to_predict)
        )
        line_2 = calculate_line_3d(
            z_positions_2, y_positions_2, x_positions_2, points=(0, -z_to_predict)
        )
        z_idx = z_to_predict - 1
        target_z = z_positions_1[z_to_predict - 1]

    # Get predictions
    predict_x_1, predict_y_1 = line_1(target_z)
    predict_x_2, predict_y_2 = line_2(target_z)

    # Check if predicted points are in cell_1's coords_set
    predicted_line_1_in_cell_1 = (
        int(round(target_z)),
        int(round(predict_y_1)),
        int(round(predict_x_1)),
    ) in cell_1.coords_set
    predicted_line_2_in_cell_1 = (
        int(round(target_z)),
        int(round(predict_y_2)),
        int(round(predict_x_2)),
    ) in cell_1.coords_set

    # print(predicted_line_1_in_cell_1, predicted_line_2_in_cell_1)
    # print(int(round(predict_y_1*0.64)), int(round(predict_x_1*0.64)), int(round(predict_y_2*0.64)), int(round(predict_x_2*0.64)))
    if not (predicted_line_1_in_cell_1 and predicted_line_2_in_cell_1):
        # print(
        #     f"  ✗ Predicted splitting points not in cell {cell_1.label} at z={int(round(target_z))}"
        # )
        return None

    pred_point_1 = np.array([predict_y_1, predict_x_1])
    pred_point_2 = np.array([predict_y_2, predict_x_2])

    # print(f"Attempting to split touching cells {cell_1.label} and {cell_2.label}")
    split_results = check_split_cells(cell_1, z_idx, pred_point_1, pred_point_2)
    if split_results is None:
        return None

    part_1_coords, part_2_coords = split_results
    target_z_int = int(round(target_z))
    return part_1_coords, part_2_coords, z_idx, target_z_int


def update_coords(cell_1, cell_2, z_idx, part_1_coords_2d, part_2_coords_2d, last_z):
    """Update both cells after splitting cell_1 at its top"""
    cell_1.coords_set_2d[z_idx] = part_1_coords_2d

    for y, x in part_2_coords_2d:
        cell_1.coords_set.discard((last_z, int(y), int(x)))

    cell_1.volumes_2d[z_idx] = len(part_1_coords_2d)
    part_1_array = np.array(list(part_1_coords_2d))
    cell_1.centroids_2d[z_idx] = (last_z, *np.mean(part_1_array, axis=0))

    # Append to cell_2
    cell_2.coords_set_2d.append(part_2_coords_2d)
    cell_2.labels_2d.append(cell_1.labels_2d[z_idx])

    part_2_array = np.array(list(part_2_coords_2d))
    cell_2.centroids_2d.append((last_z, *np.mean(part_2_array, axis=0)))
    cell_2.volumes_2d.append(len(part_2_coords_2d))

    for y, x in part_2_coords_2d:
        cell_2.coords_set.add((last_z, int(y), int(x)))

    _recalculate_cell_properties(cell_1)
    _recalculate_cell_properties(cell_2)


def update_coords_bottom(
    cell_2, cell_1, z_idx, part_1_coords_2d, part_2_coords_2d, first_z
):
    """Update both cells after splitting cell_2 at its bottom"""
    cell_2.coords_set_2d[z_idx] = part_1_coords_2d

    for y, x in part_2_coords_2d:
        cell_2.coords_set.discard((first_z, int(y), int(x)))

    cell_2.volumes_2d[z_idx] = len(part_1_coords_2d)
    part_1_array = np.array(list(part_1_coords_2d))
    cell_2.centroids_2d[z_idx] = (first_z, *np.mean(part_1_array, axis=0))

    # Insert at beginning of cell_1
    cell_1.coords_set_2d.insert(0, part_2_coords_2d)
    cell_1.labels_2d.insert(0, cell_2.labels_2d[z_idx])

    part_2_array = np.array(list(part_2_coords_2d))
    cell_1.centroids_2d.insert(0, (first_z, *np.mean(part_2_array, axis=0)))
    cell_1.volumes_2d.insert(0, len(part_2_coords_2d))

    for y, x in part_2_coords_2d:
        cell_1.coords_set.add((first_z, int(y), int(x)))

    _recalculate_cell_properties(cell_1)
    _recalculate_cell_properties(cell_2)


def _recalculate_cell_properties(cell):
    """Helper to recalculate volume and centroid after modification"""
    cell.volume = sum(cell.volumes_2d)
    cell.centroid = np.mean(cell.centroids_2d, axis=0)


import copy

def split_organoid_cells(organoid):
    print("Starting to split touching cells...")
    organoid = find_touching_pairs(organoid)
    touching_cells = find_touching_cells(organoid)
    print(f"Found {len(touching_cells)} pairs of touching cells.")
    number_of_splits = 0
    for pair in touching_cells:
        cell_1 = next(c for c in organoid if c.label == pair[0])
        cell_2 = next(c for c in organoid if c.label == pair[1])
        # Ensure cell_1 is below cell_2 (lower z centroid)
        if cell_1.centroid[0] > cell_2.centroid[0]:
            cell_1, cell_2 = cell_2, cell_1
        number_of_splits += split_multiple_cell_layers(cell_1, cell_2)
    
    print(f"Splitted {number_of_splits} touching cell pairs.")
    return organoid


def organoid_from_mask(mask):
    """Reconstruct organoid list directly from mask by splitting coords by z-level"""
    props = regionprops(mask)

    organoid = []
    for prop in props:
        # Get 3D coordinates (z, y, x)
        coords_3d = prop.coords

        # Split coordinates by z-level
        coords_by_z = {}
        for z, y, x in coords_3d:
            if z not in coords_by_z:
                coords_by_z[z] = []
            coords_by_z[z].append((y, x))

        # Sort by z to maintain order
        z_sorted = sorted(coords_by_z.keys())

        # Build per-slice data
        centroids_2d = []
        coords_set_2d = []
        volumes_2d = []

        for z in z_sorted:
            coords_2d = np.array(coords_by_z[z])
            centroid_2d = np.mean(coords_2d, axis=0)

            centroids_2d.append((z, centroid_2d[0], centroid_2d[1]))
            coords_set_2d.append(set(map(tuple, coords_2d)))
            volumes_2d.append(len(coords_2d))

        cell = cell_3d(
            label=prop.label,
            centroid=prop.centroid,
            coords_set=set(map(tuple, prop.coords)),
            volume=prop.area,
            centroids_2d=centroids_2d,
            coords_set_2d=coords_set_2d,
            volumes_2d=volumes_2d,
        )

        organoid.append(cell)

    return organoid


def stitch_small_cells(organoid, max_slices=2, iou_threshold=0.9):
    """Merge small cells (1-2 slices) with neighboring cells above or below"""
    cells_to_remove = []
    number_of_cells_stitched = 0
    number_of_cells_removed = 0

    print(f"Stitching cells with {max_slices} or fewer slices...")

    for cell in organoid:
        if len(cell.volumes_2d) > max_slices:
            continue  # Only process cells with max_slices or fewer

        # Get the z positions of this cell's slices
        z_positions = [int(round(c[0])) for c in cell.centroids_2d]

        # Find neighboring cells in organoid that are above or below
        candidates = []
        for c in organoid:
            if c.label == cell.label or len(c.volumes_2d) <= max_slices:
                continue

            # Check if candidate cell is adjacent to any of the current cell's slices
            for z_pos in z_positions:
                # Check adjacent z-levels
                for neighbor_z in [z_pos - 1, z_pos + 1]:
                    # Get the slice index in the candidate cell at neighbor_z
                    candidate_z_positions = [
                        int(round(c_cent[0])) for c_cent in c.centroids_2d
                    ]

                    if neighbor_z in candidate_z_positions:
                        # Found an adjacent slice, now check IOU
                        candidate_slice_idx = candidate_z_positions.index(neighbor_z)
                        cell_slice_idx = z_positions.index(z_pos)

                        iou = calculate_iou(
                            {
                                0: cell.coords_set_2d[cell_slice_idx],
                                1: c.coords_set_2d[candidate_slice_idx],
                            },
                            0,
                            1,
                        )

                        if iou > iou_threshold:
                            candidates.append(c)
                            break  # Found a valid neighbor, no need to check other slices of this candidate

                if c in candidates:
                    break  # Already added this candidate

        if not candidates:
            # Only remove 1-slice cells, keep 2-slice cells
            if len(cell.volumes_2d) == 1:
                cells_to_remove.append(cell.label)
                number_of_cells_removed += 1
            continue

        number_of_cells_stitched += 1
        closest_neighbor = candidates[0]

        # Add all of cell's slices to neighbor
        for i in range(len(cell.coords_set_2d)):
            # Find correct insertion position to maintain z-order
            cell_z = int(round(cell.centroids_2d[i][0]))
            neighbor_z_positions = [
                int(round(c[0])) for c in closest_neighbor.centroids_2d
            ]

            # Find insertion index
            insert_idx = len(neighbor_z_positions)
            for idx, neighbor_z in enumerate(neighbor_z_positions):
                if cell_z < neighbor_z:
                    insert_idx = idx
                    break

            # Insert at correct position
            closest_neighbor.coords_set_2d.insert(insert_idx, cell.coords_set_2d[i])
            closest_neighbor.centroids_2d.insert(insert_idx, cell.centroids_2d[i])
            closest_neighbor.volumes_2d.insert(insert_idx, cell.volumes_2d[i])

            # Update 3D coords_set
            closest_neighbor.coords_set.update(
                {(cell_z, int(y), int(x)) for y, x in cell.coords_set_2d[i]}
            )

        # Update neighbor properties
        _recalculate_cell_properties(closest_neighbor)

        # Mark cell for removal
        cells_to_remove.append(cell.label)

    # Remove merged cells from organoid
    organoid = [c for c in organoid if c.label not in cells_to_remove]

    print(
        f"Stitched {number_of_cells_stitched} small cells, and removed {number_of_cells_removed} cells without suitable neighbors."
    )

    return organoid

import copy

def stitch_3d(mask, image1, image_type_1=None, image2=None, image_type_2=None, breaking_threshold=2.5):
    print("Starting 3D stitching process...")
    organoid = get_2d_mask_properties(mask, image1, image_type_1=image_type_1, image2=image2, image_type_2=image_type_2)
    print(f"Initial organoid has {len(organoid)} 2d sliced cells.")
    organoid = IOU_stitching(organoid, distance_threshold=10, iou_threshold=0.3)

    # Iterative break and restitching
    max_iterations = 10
    iteration = 0
    print("Starting iterative breaking of cells")
    while iteration < max_iterations:
        organoid = get_break_scores(organoid)
        organoid, breaks_made = break_stitching(organoid, breaking_threshold=breaking_threshold)
        if breaks_made == 0:
            break  # No more breaks made

        print(f"    Iteration {iteration + 1}: Made {breaks_made} breaks.")
        iteration += 1

    # before_splitting = copy.deepcopy(organoid)
    # before_splitting_mask = mask_from_organoid(before_splitting, shape=mask.shape)
    organoid = split_organoid_cells(organoid)

    stitched_mask = mask_from_organoid(organoid, shape=mask.shape)
    organoid = organoid_from_mask(stitched_mask)

    organoid = stitch_small_cells(organoid)

    stitched_mask = mask_from_organoid(organoid, shape=mask.shape)
    

    print(f"Final stitched mask has {len(organoid)} cells.")

    return stitched_mask, organoid #, before_splitting, before_splitting_mask

In [8]:
import time
import napari


output_directory = r"C:\Users\6331823\Local SSD\Fake_data"
image = tifffile.imread(os.path.join(output_directory, "realistic_organoid.tif"))
mask = tifffile.imread(
    os.path.join(output_directory, "realistic_organoid_segmented.tif")
)
perfect_mask = tifffile.imread(
    os.path.join(output_directory, "perfect_mask.tif")
)

# organoid = get_2d_mask_properties(mask, image, image_type_1="wt")
# organoid = IOU_stitching(organoid, distance_threshold=10, iou_threshold=0.3)
# stitched_mask = mask_from_organoid(organoid, mask.shape)
start_time = time.time()    
stitched_mask, organoid, before_splitting_mask = stitch_3d(
    mask,
    image,
    image_type_1="wt",
    breaking_threshold=2,
)
end_time = time.time()
print(f"Stitching completed in {end_time - start_time:.2f} seconds.")

# tifffile.imwrite(
#     os.path.join(output_directory, "3d_segmented.tif"), stitched_mask
# )

# print(centroid_accuracy(perfect_mask, stitched_mask))
# print(f"actual amount of cells: {len(np.unique(perfect_mask)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask)) - 1}")
scale = (2.5, 0.64, 0.64)
viewer = napari.Viewer()
viewer.add_image(image, name="wt image", blending="additive", scale=scale)
viewer.add_labels(mask, name="original mask", visible=False, scale=scale)
viewer.add_labels(stitched_mask, name="stitched mask", visible=False, scale=scale)
viewer.add_labels(perfect_mask, name="perfect mask", visible=False, scale=scale)
viewer.add_labels(before_splitting_mask, name="before split mask", visible=False, scale=scale)

Starting 3D stitching process...
Initial organoid has 1864 2d sliced cells.
Starting IOU based 3D stitching...
Completed IOU based stitching: 178 cells formed.
Starting iterative breaking of cells
    Iteration 1: Made 20 breaks.
    Iteration 2: Made 9 breaks.
    Iteration 3: Made 1 breaks.
Starting to split touching cells...
Found 108 pairs of touching cells.
Splitted 20 touching cell pairs.
Stitching cells with 2 or fewer slices...
Stitched 7 small cells, and removed 1 cells without suitable neighbors.
Final stitched mask has 200 cells.
Stitching completed in 4.01 seconds.

In [10]:
output_directory = r"C:\Users\6331823\Local SSD\Data_Merel\Image optimisation\Plate14_20x_2x2bin_2.5um_F0"
image = tifffile.imread(os.path.join(output_directory, "cropped", "Frame-0.tif"))
stitched_mask = tifffile.imread(
    os.path.join(output_directory, "segmented", "Frame-0_masks.tif")
)


scale = (2.5, 0.64, 0.64)
viewer = napari.Viewer()
viewer.add_image(image[:, 0], name="wt image", blending="additive", scale=scale)
viewer.add_labels(stitched_mask, name="stitched mask", visible=False, scale=scale)

In [6]:
import time
output_directory = r"C:\Users\6331823\Local SSD\Data_Merel\MvL_Exp139_positions_WT_SI\Experiment_final_1_F02"
image = tifffile.imread(os.path.join(output_directory, "cropped", "Frame-20.tif"))[:,:,:,:606]
mask = tifffile.imread(
    os.path.join(output_directory, "segmented", "Frame-20_masks.tif")
)
# perfect_mask = tifffile.imread(os.path.join(output_directory, "perfect_mask.tif"))

start_time = time.time()
stitched_mask, organoid = stitch_3d(
    mask,
    image1=image[:,0],
    image_type_1="crc",
    image2=image[:,1],
    image_type_2="wt",
    breaking_threshold=2.5,
)
end_time = time.time()
print(f"Stitching completed in {end_time - start_time:.2f} seconds.")

# tifffile.imwrite(
#     os.path.join(output_directory, "3d_segmented.tif"), stitched_mask
# )

# print(centroid_accuracy(perfect_mask, stitched_mask))
# print(f"actual amount of cells: {len(np.unique(perfect_mask)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask)) - 1}")
scale = (2.5, 0.64, 0.64)
viewer = napari.Viewer()
viewer.add_image(image[:,0], name="wt image", blending="additive", scale=scale)
viewer.add_image(image[:,1], name="crc image", blending="additive", scale=scale)
viewer.add_labels(mask, name="original mask", visible=False, scale=scale)
viewer.add_labels(stitched_mask, name="stitched mask", visible=False, scale=scale)
# viewer.add_labels(perfect_mask, name="perfect mask", visible=False, scale=scale)
# viewer.add_labels(
#     before_splitting_mask, name="before split mask", visible=False, scale=scale
# )

Starting 3D stitching process...
Initial organoid has 448 2d sliced cells.
Starting IOU based 3D stitching...
Completed IOU based stitching: 213 cells formed.
Starting iterative breaking of cells
    Iteration 1: Made 3 breaks.
Starting to split touching cells...
Found 145 pairs of touching cells.
Splitted 7 touching cell pairs.
Stitching cells with 2 or fewer slices...
Stitched 1 small cells, and removed 90 cells without suitable neighbors.
Final stitched mask has 125 cells.
Stitching completed in 0.23 seconds.

Suijkerbuijk segmentation

In [ ]:
import os
import sys

sys.path.insert(0, os.path.dirname(os.getcwd()))
import utils
import time

input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1"
# input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Zebrafish_1"
# input_directory = r"C:\Users\6331823\Local SSD\Fake_data"
# input_directory = r"C:\Users\6331823\Downloads\Data for mario\Merel organoid"
# input_directory = r"C:\Users\6331823\Local SSD\Data_Merel\MvL_Exp139_positions_WT_SI\Experiment_final_1_F18"

image = tifffile.imread(os.path.join(input_directory, "data.tif"))

# model = utils.load_model(
#     r"C:\Users\6331823\Local SSD\Train dual nuclei 20x\models\dual_nuclei_wt"
# )
model = utils.load_model(r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1\model\drosophila")
# model = utils.load_model(
#     r"C:\Users\6331823\Local SSD\Train fixed intestinal 40x\models\fixed_intestinal_40x"
# )
# model = utils.load_model(
#     r"C:\Users\6331823\Local SSD\Train model cell segmentation\models\cell_segmentation_4"
# )

start_time = time.time()
# mask = utils.segment(image, model)
# tifffile.imwrite(
#     os.path.join(input_directory, "2d_segmented_drosophila_model.tif"),
#     mask,
#     compression="zlib",
#     compressionargs={"level": 8},
# )
mask = tifffile.imread(os.path.join(input_directory, "2d_segmented_drosophila_model.tif"))
segmentation_time = time.time() - start_time


start_stitch_time = time.time()
stitched_mask, organoid = stitch_3d(
    mask,
    image,
    image_type_1="wt",
    breaking_threshold=2,
)
end_time = time.time()

tifffile.imwrite(
    os.path.join(input_directory, "3d_segmented_suijkerbuijk_drosophila_model.tif"),
    stitched_mask,
    compression="zlib",
    compressionargs={"level": 8},
)

# ground_truth = tifffile.imread(
#     os.path.join(input_directory, "GroundTruth.tif")
# )

# results = (centroid_accuracy(ground_truth, stitched_mask))
# print(f"centroid accuracy: {results}")
# print(
#     f"actual amount of cells: {len(np.unique(ground_truth)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask)) - 1}"
# )

print(f"Segmentation completed in {segmentation_time:.2f} seconds.")
print(f"Stitching completed in {end_time - start_stitch_time:.2f} seconds.")
print(f"Total time: {end_time - start_time:.2f} seconds.")

# save results of centroid accuracy and cell count to a text file
# with open(os.path.join(input_directory, "results.txt"), "w") as f:
#     f.write(f"centroid accuracy: {results}\n")
#     f.write(
#         f"actual amount of cells: {len(np.unique(ground_truth)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask)) - 1}\n"
#     )
#     f.write(f"Segmentation time: {segmentation_time:.2f} seconds.\n")
#     f.write(f"Stitching time: {end_time - start_stitch_time:.2f} seconds.\n")
#     f.write(f"Total time: {end_time - start_time:.2f} seconds.\n")

Using CUDA for processing.
2026-02-04 14:16:41,186 [INFO] ** TORCH CUDA version installed and working. **
2026-02-04 14:16:41,186 [INFO] >>>> using GPU (CUDA)
2026-02-04 14:16:41,186 [WARNING] pretrained model C:\Users\6331823\.cellpose\models\cpsam not found, using default model
2026-02-04 14:16:42,323 [INFO] >>>> loading model C:\Users\6331823\.cellpose\models\cpsam
loaded custom model: drosophila
Starting 3D stitching process...
Initial organoid has 11261 2d sliced cells.
Starting IOU based 3D stitching...
Completed IOU based stitching: 1274 cells formed.
Starting iterative breaking of cells

TypeError: 'numpy.int32' object is not callable

Cellpose 4

In [ ]:
import os
import time
import sys
from cellpose import models, io

# input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1"
# input_directory = r"C:\Users\6331823\Local SSD\Fake_data"
# input_directory = r"C:\Users\6331823\Downloads\Data for mario\Merel organoid"
input_directory = r"C:\Users\6331823\Local SSD\Data_Merel\MvL_Exp139_positions_WT_SI\Experiment_final_1_F18"

image = tifffile.imread(os.path.join(input_directory, "data_2.tif"))

# model = models.CellposeModel(gpu=True)
sys.path.insert(0, os.path.dirname(os.getcwd()))
import utils
model = utils.load_model(
    r"C:\Users\6331823\Local SSD\Train dual nuclei 20x\models\dual_nuclei_wt"
)
# model = utils.load_model(
#     r"C:\Users\6331823\Local SSD\Train fixed intestinal 40x\models\fixed_intestinal_40x"
# )
start_time = time.time()

stitched_mask, _, _ = model.eval(
            image,
            diameter=None,
            normalize=True,
            invert=False,
            resample=True,
            do_3D=True,
            flow3D_smooth=0.4,
            progress=None,
            z_axis=0,
            anisotropy=1,
            min_size=15,
        )

segmentation_time = time.time() - start_time
end_time = time.time()

tifffile.imwrite(
    os.path.join(input_directory, "3d_segmented_cellpose4.tif"),
    stitched_mask
)

# ground_truth = tifffile.imread(os.path.join(input_directory, "GroundTruth.tif"))

# results = centroid_accuracy(ground_truth, stitched_mask)
# print(f"centroid accuracy: {results}")
# print(
#     f"actual amount of cells: {len(np.unique(ground_truth)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask)) - 1}"
# )

print(f"Segmentation completed in {segmentation_time:.2f} seconds.")
print(f"Total time: {end_time - start_time:.2f} seconds.")

# # save results of centroid accuracy and cell count to a text file
# with open(os.path.join(input_directory, "results_cellpose4.txt"), "w") as f:
#     f.write(f"centroid accuracy: {results}\n")
#     f.write(
#         f"actual amount of cells: {len(np.unique(ground_truth)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask)) - 1}\n"
#     )
#     f.write(f"Segmentation time: {segmentation_time:.2f} seconds.\n")
#     f.write(f"Stitching time: {end_time - start_stitch_time:.2f} seconds.\n")
#     f.write(f"Total time: {end_time - start_time:.2f} seconds.\n")

Using CUDA for processing.
loaded custom model: dual_nuclei
Segmentation completed in 41.79 seconds.
Total time: 41.79 seconds.

In [22]:
print(f"predicted amount of cells: {len(np.unique(stitched_mask)) - 1}")

predicted amount of cells: 8755

In [3]:
viewer = napari.Viewer()
# input_directory = r"C:\Users\6331823\Downloads\Data for mario\Merel organoid"
input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1"
# input_directory = r"C:\Users\6331823\Local SSD\Data_Merel\MvL_Exp139_positions_WT_SI\Experiment_final_1_F18"
image = tifffile.imread(os.path.join(input_directory, "data_3.tif"))
suijkerbuijk = tifffile.imread(
    os.path.join(input_directory, "3d_segmented_suijkerbuijk.tif")
)
cellpose4 = tifffile.imread(
    os.path.join(input_directory, "3d_segmented_cellpose4.tif")
)
# ground_truth = tifffile.imread(
#     os.path.join(input_directory, "GroundTruth.tif")
# )

scale = (2.5, 0.32, 0.32)
viewer.add_image(image, name="wt image", blending="additive", scale=scale)
viewer.add_labels(suijkerbuijk, name="suijkerbuijk mask", visible=False, scale=scale)
viewer.add_labels(cellpose4, name="cellpose4 mask", visible=False, scale=scale)
# viewer.add_labels(ground_truth, name="ground truth", visible=False, scale=scale)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\6331823\\Downloads\\NIS3D\\NIS3D\\NIS3D\\Drosophila_1\\data_3.tif'

In [14]:
print(f"predicted amount of cells: {len(np.unique(suijkerbuijk)) - 1}")

predicted amount of cells: 855

In [55]:
import os
import tifffile

def get_segmentation_score(input_directory):
    # ground_truth = tifffile.imread(
    #     os.path.join(input_directory, "GroundTruth.tif")
    # )
    ground_truth = tifffile.imread(
        os.path.join(input_directory, "perfect_mask.tif")
    )
    stitched_mask_suijkerbuijk = tifffile.imread(
        os.path.join(input_directory, "3d_segmented.tif")
    )
    image = tifffile.imread(os.path.join(input_directory, "realistic_organoid.tif"))
    stitched_mask_cp4 = tifffile.imread(os.path.join(input_directory, "realistic_organoid_cp_masks.tif"))
    results_cp4 = centroid_accuracy(ground_truth, stitched_mask_cp4)
    results_suijkerbuijk = centroid_accuracy(ground_truth, stitched_mask_suijkerbuijk)
    cell_count_info = (
        f"actual amount of cells: {len(np.unique(ground_truth)) - 1}, predicted amount of cells: {len(np.unique(stitched_mask_suijkerbuijk)) - 1}"
    )

    scale = (2.5, 0.64, 0.64)
    viewer = napari.Viewer()
    viewer.add_image(image, name="wt image", blending="additive", scale=scale)
    # viewer.add_labels(ground_truth, name="perfect mask", visible=False)
    viewer.add_labels(stitched_mask_cp4, name="cp4 stitched mask", visible=False, scale=scale)
    viewer.add_labels(stitched_mask_suijkerbuijk, name="suijkerbuijk stitched mask", visible=False, scale=scale)
    return results_cp4, results_suijkerbuijk, cell_count_info

# input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Zebrafish_1"
input_directory = r"C:\Users\6331823\Local SSD\Fake_data"

results_cp4, results_suijkerbuijk, cell_count_info = get_segmentation_score(input_directory)
print(results_cp4)
print(results_suijkerbuijk)
print(cell_count_info)

{'true_positives': 200, 'false_negatives': 0, 'false_positives': 3, 'merged_cells': 0, 'precision': 0.9852216748768473, 'recall': 1.0, 'f1': 0.9925558312655086, 'voxel_dice': 0.6218564047190718, 'false_positive_labels': [201, 202, 203]}
{'true_positives': 200, 'false_negatives': 0, 'false_positives': 0, 'merged_cells': 0, 'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'voxel_dice': 0.5385429021272464, 'false_positive_labels': []}
actual amount of cells: 200, predicted amount of cells: 200

In [5]:
import napari
import tifffile
import os

# input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1"
input_directory = r"C:\Users\6331823\Local SSD\Fake_data"

image = tifffile.imread(os.path.join(input_directory, "data.tif"))
stitched_mask = tifffile.imread(os.path.join(input_directory, "3d_segmented.tif"))

ground_truth = tifffile.imread(os.path.join(input_directory, "GroundTruth.tif"))
viewer = napari.Viewer()
# scale = (1,1,1)
scale = (2.5, 0.62, 0.62)
viewer.add_image(image, name="zebrafish 1 image", blending="additive", scale=scale)
viewer.add_labels(stitched_mask, name="3d stitched mask", visible=False, scale=scale)
viewer.add_labels(ground_truth, name="ground truth", visible=False, scale=scale)

In [3]:
from functools import lru_cache
import time
import tifffile

def weighted_metrics(ground_truth, prediction, confidence_map=None):
    """
    Calculate weighted precision, recall, F1, IoU, and SEG scores (memory-efficient version).
    """
    start_total = time.time()

    ground_truth = np.asarray(ground_truth, dtype=np.uint32)
    prediction = np.asarray(prediction, dtype=np.uint32)

    if ground_truth.shape != prediction.shape:
        raise ValueError("Masks must share shape")

    if confidence_map is not None:
        confidence_map = np.asarray(confidence_map, dtype=np.uint8)
        if confidence_map.shape != ground_truth.shape:
            raise ValueError("Confidence map must have same shape as masks")

    # Get unique labels (excluding background)
    gt_labels = np.unique(ground_truth)
    gt_labels = gt_labels[gt_labels > 0]
    pred_labels = np.unique(prediction)
    pred_labels = pred_labels[pred_labels > 0]

    print(
        f"Processing {len(gt_labels)} GT cells and {len(pred_labels)} predicted cells..."
    )

    # Build confidence scores
    confidence_scores = {}
    start_conf = time.time()

    if confidence_map is not None:
        conf_value_to_score = np.array([0.0, 0.0, 1 / 3, 2 / 3, 1.0], dtype=np.float32)

        for gt_label in gt_labels:
            gt_mask = ground_truth == gt_label
            cell_conf_values = confidence_map[gt_mask]
            undefined_ratio = np.sum(cell_conf_values == 1) / len(cell_conf_values)

            if undefined_ratio > 0.5:
                confidence_scores[gt_label] = 0.0
                continue

            valid_mask = cell_conf_values != 1
            if np.any(valid_mask):
                valid_pixels = cell_conf_values[valid_mask]
                weighted_conf = np.mean(conf_value_to_score[valid_pixels])
                confidence_scores[gt_label] = float(weighted_conf)
            else:
                confidence_scores[gt_label] = 0.0
    else:
        for gt_label in gt_labels:
            confidence_scores[gt_label] = 1.0

    valid_gt_labels = np.array(
        [l for l in gt_labels if confidence_scores.get(l, 0) > 0]
    )
    print(
        f"  Confidence calculation done: {time.time() - start_conf:.2f}s ({len(valid_gt_labels)} valid GT cells)"
    )

    # Compute centroids WITHOUT storing full masks
    start_spatial = time.time()
    print(f"  Computing centroids and IoU for nearby cells...")

    gt_centroids = {}
    pred_centroids = {}

    # Only compute centroids for valid GT labels
    for gt_label in valid_gt_labels:
        coords = np.where(ground_truth == gt_label)
        gt_centroids[int(gt_label)] = np.array(
            [np.mean(coords[0]), np.mean(coords[1]), np.mean(coords[2])]
        )

    for pred_label in pred_labels:
        coords = np.where(prediction == pred_label)
        pred_centroids[int(pred_label)] = np.array(
            [np.mean(coords[0]), np.mean(coords[1]), np.mean(coords[2])]
        )

    # Build KDTree for fast nearest neighbor queries
    from scipy.spatial import cKDTree

    gt_centroids_array = np.array([gt_centroids[int(l)] for l in valid_gt_labels])
    pred_centroids_array = np.array([pred_centroids[int(l)] for l in pred_labels])

    pred_tree = cKDTree(pred_centroids_array)

    # Only compute IoU for nearby cells - compute masks on-the-fly
    max_distance = 100
    k_neighbors = 5

    iou_matrix = {}
    computed_ious = 0

    for i, gt_label in enumerate(valid_gt_labels):
        gt_label = int(gt_label)

        # Find nearby prediction cells
        distances, indices = pred_tree.query(
            gt_centroids_array[i], k=min(k_neighbors, len(pred_labels))
        )

        iou_row = {}

        # Create GT mask once per cell
        gt_mask = ground_truth == gt_label

        for idx, dist in zip(indices, distances):
            # Skip if too far away
            if dist > max_distance:
                continue

            pred_label = int(pred_labels[idx])

            # Create pred mask on-the-fly (small memory footprint)
            pred_mask = prediction == pred_label

            intersection = np.count_nonzero(gt_mask & pred_mask)
            if intersection == 0:
                continue  # Skip non-overlapping pairs

            union = np.count_nonzero(gt_mask | pred_mask)
            iou_row[pred_label] = intersection / union if union > 0 else 0.0
            computed_ious += 1

            # Delete pred_mask immediately to free memory
            del pred_mask

        del gt_mask  # Free GT mask for this cell
        iou_matrix[gt_label] = iou_row

    print(
        f"  IoU calculation done: {time.time() - start_spatial:.2f}s (computed {computed_ious} IoU pairs)"
    )

    # Matching
    start_match = time.time()
    print(f"  Finding best matches...")
    gt_matches = {}
    matched_pred_labels = set()

    for gt_label in valid_gt_labels:
        gt_label = int(gt_label)
        iou_row = iou_matrix.get(gt_label, {})

        if not iou_row:
            gt_matches[gt_label] = (None, 0.0)
            continue

        best_pred_label, best_iou = max(iou_row.items(), key=lambda x: x[1])

        # Check bidirectional match
        pred_best_gt_score = 0
        pred_best_gt = None

        for other_gt in valid_gt_labels:
            other_gt = int(other_gt)
            if best_pred_label in iou_matrix.get(other_gt, {}):
                score = iou_matrix[other_gt][best_pred_label]
                if score > pred_best_gt_score:
                    pred_best_gt_score = score
                    pred_best_gt = other_gt

        if pred_best_gt == gt_label:
            gt_matches[gt_label] = (best_pred_label, best_iou)
            matched_pred_labels.add(best_pred_label)
        else:
            gt_matches[gt_label] = (None, 0.0)

    print(
        f"  Matching done: {time.time() - start_match:.2f}s ({len(matched_pred_labels)} matches found)"
    )

    # Calculate metrics (final pass - compute on-the-fly)
    start_metrics = time.time()
    W_TP = 0.0
    W_FN = 0.0
    weighted_seg_numerator = 0.0

    for gt_label in valid_gt_labels:
        gt_label = int(gt_label)
        confidence = confidence_scores.get(gt_label, 1.0)
        matched_pred, iou_score = gt_matches[gt_label]

        if matched_pred is not None:
            W_TP += confidence
            weighted_seg_numerator += confidence * iou_score
        else:
            W_FN += confidence

    FP = len(pred_labels) - len(matched_pred_labels)

    W_Precision = W_TP / (W_TP + FP) if (W_TP + FP) > 0 else 0.0
    W_Recall = W_TP / (W_TP + W_FN) if (W_TP + W_FN) > 0 else 0.0
    W_F1 = (2 * W_TP) / (2 * W_TP + FP + W_FN) if (2 * W_TP + FP + W_FN) > 0 else 0.0

    # Compute binary metrics on-the-fly (no large intermediate arrays)
    gt_binary = ground_truth > 0
    pred_binary = prediction > 0
    intersection_mask = gt_binary & pred_binary

    # Recompute confidence weight map only for pixels needed
    if confidence_map is not None:
        conf_value_to_score = np.array([0.0, 0.0, 1 / 3, 2 / 3, 1.0], dtype=np.float32)
        W_IoU_numerator = 0.0
        for gt_label in valid_gt_labels:
            mask = (ground_truth == gt_label) & intersection_mask
            if np.any(mask):
                conf_vals = conf_value_to_score[confidence_map[mask]]
                W_IoU_numerator += len(mask) * np.mean(conf_vals)
    else:
        W_IoU_numerator = np.count_nonzero(intersection_mask)

    W_IoU_denominator = np.count_nonzero(gt_binary) + np.count_nonzero(
        pred_binary & ~gt_binary
    )
    W_IoU = W_IoU_numerator / W_IoU_denominator if W_IoU_denominator > 0 else 0.0

    W_SEG = (
        weighted_seg_numerator / (W_TP + W_FN + FP) if (W_TP + W_FN + FP) > 0 else 0.0
    )

    print(f"  Metrics calculation done: {time.time() - start_metrics:.2f}s")
    print(f"Total time: {time.time() - start_total:.2f}s\n")

    return {
        "W-TP": W_TP,
        "W-FN": W_FN,
        "FP": FP,
        "W-Precision": W_Precision,
        "W-Recall": W_Recall,
        "W-F1": W_F1,
        "W-IoU": W_IoU,
        "W-SEG": W_SEG,
        "num_gt_cells": len(valid_gt_labels),
        "num_pred_cells": len(pred_labels),
        "num_matched": len(matched_pred_labels),
    }


input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1"

confidence_map = tifffile.imread(
    os.path.join(input_directory, "ConfidenceScore.tif")
)

stitched_mask = tifffile.imread(os.path.join(input_directory, "3d_segmented.tif"))

ground_truth = tifffile.imread(os.path.join(input_directory, "GroundTruth.tif"))

# Calculate weighted metrics
results = weighted_metrics(ground_truth, stitched_mask, confidence_map)
print(f"W-Precision: {results['W-Precision']:.3f}")
print(f"W-Recall: {results['W-Recall']:.3f}")
print(f"W-F1: {results['W-F1']:.3f}")
print(f"W-SEG: {results['W-SEG']:.3f}")
print(f"W-IoU: {results['W-IoU']:.3f}")

Processing 1694 GT cells and 1683 predicted cells...
  Confidence calculation done: 160.95s (1694 valid GT cells)
  Computing centroids and IoU for nearby cells...

KeyboardInterrupt:

In [ ]:
print(f"W-F1: {results['W-F1']:.3f}")
print(f"W-Precision: {results['W-Precision']:.3f}")
print(f"W-Recall: {results['W-Recall']:.3f}")
print(f"W-IoU: {results['W-IoU']:.3f}")
print(f"W-SEG: {results['W-SEG']:.3f}")
print(f"Time = 220 seconds")

In [19]:
import numpy as np
from skimage.measure import regionprops
from tqdm import tqdm


def centroid_accuracy(ground_truth_mask, predicted_mask):
    ground_truth_mask = np.asarray(ground_truth_mask)
    predicted_mask = np.asarray(predicted_mask)
    if ground_truth_mask.shape != predicted_mask.shape:
        raise ValueError("Masks must share shape")

    gt_props = regionprops(ground_truth_mask)
    pred_props = regionprops(predicted_mask)

    # Precompute coordinate sets for ALL cells upfront
    gt_coords_sets = {prop.label: set(map(tuple, prop.coords)) for prop in gt_props}
    pred_coords_sets = {prop.label: set(map(tuple, prop.coords)) for prop in pred_props}

    hit_pred_labels = set()
    predicted_labels = np.array([])
    per_cell_iou = {}
    tp = fn = 0

    # Main loop with progress bar
    for prop in tqdm(gt_props, desc="Computing centroid accuracy", unit="cell"):
        gt_label = prop.label
        centroid = np.rint(prop.centroid).astype(int)
        centroid = tuple(np.clip(centroid, 0, np.array(ground_truth_mask.shape) - 1))
        pred_label = predicted_mask[centroid]
        predicted_labels = np.append(predicted_labels, pred_label)

        if pred_label > 0:
            tp += 1
            hit_pred_labels.add(int(pred_label))

            # Fast IoU using precomputed sets
            gt_set = gt_coords_sets[gt_label]
            pred_set = pred_coords_sets[pred_label]

            intersection = len(gt_set & pred_set)
            union = len(gt_set | pred_set)
            cell_iou = intersection / union if union > 0 else 0.0

            per_cell_iou[gt_label] = cell_iou
        else:
            fn += 1
            per_cell_iou[gt_label] = 0.0

    pred_labels = set(np.unique(predicted_mask))
    pred_labels.discard(0)
    fp = len(pred_labels - hit_pred_labels)
    fp_list = list(pred_labels - hit_pred_labels)
    merged_cells = len(predicted_labels) - len(np.unique(predicted_labels))

    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if precision + recall else 0.0

    gt_binary = ground_truth_mask > 0
    pred_binary = predicted_mask > 0
    intersection = np.count_nonzero(gt_binary & pred_binary)
    dice = (
        (2 * intersection) / (gt_binary.sum() + pred_binary.sum())
        if (gt_binary.sum() + pred_binary.sum())
        else 0.0
    )

    # Calculate 3D IoU
    union = np.count_nonzero(gt_binary | pred_binary)
    iou_3d = intersection / union if union > 0 else 0.0

    return {
        "true_positives": tp,
        "false_negatives": fn,
        "false_positives": fp,
        "merged_cells": merged_cells,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "voxel_dice": dice,
        "iou_3d": iou_3d,
        "per_cell_iou": per_cell_iou,
        "false_positive_labels": fp_list,
    }

In [ ]:
import os
import tifffile

input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Zebrafish_1"

image = tifffile.imread(os.path.join(input_directory, "data.tif"))

stitched_mask = tifffile.imread(
    os.path.join(input_directory, "3d_segmented_suijkerbuijk_drosophila_model.tif"),
)

cp4 = tifffile.imread(
    os.path.join(input_directory, "data_cp_masks.tif"),
)

ground_truth = tifffile.imread(
    os.path.join(input_directory, "GroundTruth.tif")
)

results_suijkerbuijk = centroid_accuracy(ground_truth, stitched_mask)
print(results_suijkerbuijk)
mean_iou_suijkerbuijk = np.mean(list(results_suijkerbuijk["per_cell_iou"].values()))
print(f"Mean IoU Suijkerbuijk: {mean_iou_suijkerbuijk:.3f}")

results_cp4 = centroid_accuracy(ground_truth, cp4)
print(results_cp4)
mean_iou_cp4 = np.mean(list(results_cp4["per_cell_iou"].values()))
print(f"Mean IoU CP4: {mean_iou_cp4:.3f}")

Computing centroid accuracy: 100%|██████████| 12793/12793 [00:05<00:00, 2383.09cell/s]

{'true_positives': 12376, 'false_negatives': 417, 'false_positives': 1360, 'merged_cells': 718, 'precision': 0.900990099009901, 'recall': 0.9674040490893457, 'f1': 0.9330166987070753, 'voxel_dice': 0.6847328458817838, 'iou_3d': 0.5206036231786262, 'per_cell_iou': {1: 0.5790527018012008, 2: 0.6065759637188208, 3: 0.38507847774672116, 4: 0.4475402699172834, 5: 0.0, 6: 0.5617726051924798, 7: 0.47619047619047616, 8: 0.5824104234527687, 9: 0.45702952842661965, 10: 0.5433596118859915, 11: 0.5547013601419278, 12: 0.5190905190905191, 13: 0.4256014256014256, 14: 0.584247258225324, 15: 0.4115025466893039, 16: 0.5481814773153356, 17: 0.468034727703236, 18: 0.3624511082138201, 19: 0.5390977443609023, 20: 0.10593434343434344, 21: 0.42330651440436023, 22: 0.46866791744840525, 23: 0.5578734858681023, 24: 0.5700389105058365, 25: 0.46203623813632444, 26: 0.5357905982905983, 27: 0.5074404761904762, 28: 0.414651493598862, 29: 0.516914749661705, 30: 0.2799145299145299, 31: 0.35561497326203206, 32: 0.5513059701492538, 33: 0.43743536711478803, 34: 0.3885411651420318, 35: 0.42108585858585856, 36: 0.5370487650411653, 37: 0.18907337975361543, 38: 0.4314159292035398, 39: 0.31512605042016806, 40: 0.14739884393063585, 41: 0.19694622704138084, 42: 0.5574374079528719, 43: 0.37800422995577776, 44: 0.564179104477612, 45: 0.27489789506754636, 46: 0.3952941176470588, 47: 0.20639332870048646, 48: 0.19261477045908185, 49: 0.4810126582278481, 50: 0.4908095424325381, 51: 0.2937853107344633, 52: 0.6117729502452698, 53: 0.5655550479671083, 54: 0.5727619855748833, 55: 0.21495327102803738, 56: 0.3823008849557522, 57: 0.485167837626854, 58: 0.38423295454545453, 59: 0.5123674911660777, 60: 0.4392156862745098, 61: 0.4270498392282958, 62: 0.4063615709185329, 63: 0.43248782987445555, 64: 0.45134383688600554, 65: 0.21174004192872117, 66: 0.5227272727272727, 67: 0.22653942285844125, 68: 0.3600525624178712, 69: 0.41513292433537835, 70: 0.26659230340211937, 71: 0.5580508474576271, 72: 0.44452222611130554, 73: 0.5614104595879557, 74: 0.580964153275649, 75: 0.4281972937581842, 76: 0.46417445482866043, 77: 0.36174365647365, 78: 0.36273701566364386, 79: 0.39695636230289694, 80: 0.19769857759309573, 81: 0.3791838606143971, 82: 0.5161839863713799, 83: 0.5924895688456189, 84: 0.31932225480612575, 85: 0.4841549295774648, 86: 0.43475126171593365, 87: 0.4222222222222222, 88: 0.611189468735308, 89: 0.5220718069452619, 90: 0.3941994672980172, 91: 0.55125284738041, 92: 0.34726545131169406, 93: 0.3144950287807431, 94: 0.49214659685863876, 95: 0.47704685281590153, 96: 0.342220722240972, 97: 0.17860262008733624, 98: 0.19246861924686193, 99: 0.44706778370144706, 100: 0.48750557786702364, 101: 0.6420996818663839, 102: 0.5405607476635514, 103: 0.2633628318584071, 104: 0.43821510297482835, 105: 0.33892718010188794, 106: 0.4706527701590784, 107: 0.35410557184750735, 108: 0.5275229357798165, 109: 0.425673428666445, 110: 0.3210197710718002, 111: 0.519811320754717, 112: 0.4389261744966443, 113: 0.44148742253007656, 114: 0.5211459754433834, 115: 0.4717391304347826, 116: 0.6130711393869288, 117: 0.4784705477092663, 118: 0.5271072417886822, 119: 0.3565597667638484, 120: 0.2537216828478964, 121: 0.48894601542416455, 122: 0.6129271916790491, 123: 0.5355125100887813, 124: 0.5817091454272864, 125: 0.4251928020565553, 126: 0.48960066555740434, 127: 0.39237490071485304, 128: 0.4861580013504389, 129: 0.48747731397459165, 130: 0.44378966455122393, 131: 0.5405797101449276, 132: 0.3890457368718238, 133: 0.34890965732087226, 134: 0.5366403607666291, 135: 0.42382271468144045, 136: 0.564625850340136, 137: 0.35826001955034215, 138: 0.17014341590612778, 139: 0.5362962962962963, 140: 0.3836996336996337, 141: 0.3111239860950174, 142: 0.21587766390108995, 143: 0.3725950258094791, 144: 0.6490125673249552, 145: 0.3625099920063949, 146: 0.5239074550128535, 147: 0.6095278604849, 148: 0.6910592255125285, 149: 0.4825298540468819, 150: 0.43258565442445157, 151: 0.39215070643642075, 152: 0.5950974601299468, 153: 0.3755296610169492, 154: 0.2616662594673833, 155: 0.5721925133689839, 156: 0.2693877551020408, 157: 0.370020964360587, 158: 0.5282451923076923, 159: 0.5467523197715917, 160: 0.43339960238568587, 161: 0.510803324099723, 162: 0.503859649122807, 163: 0.5271493212669683, 164: 0.19911504424778761, 165: 0.64504054897068, 166: 0.6245989304812835, 167: 0.3319910514541387, 168: 0.21482778750729714, 169: 0.5181030086690463, 170: 0.22796227962279622, 171: 0.5199757869249395, 172: 0.6672113289760349, 173: 0.49259757738896365, 174: 0.5043270665472993, 175: 0.46468184471687096, 176: 0.20719424460431654, 177: 0.3080568720379147, 178: 0.5798525798525799, 179: 0.2607758620689655, 180: 0.3925898203592814, 181: 0.31859070464767614, 182: 0.2766845557543232, 183: 0.42223610243597753, 184: 0.4167601945379723, 185: 0.3574144486692015, 186: 0.5483291412145167, 187: 0.3628691983122363, 188: 0.37871631008613504, 189: 0.3810842896715473, 190: 0.6060442525634107, 191: 0.40910956093557654, 192: 0.57991513437058, 193: 0.29897218863361547, 194: 0.5094850948509485, 195: 0.5534883720930233, 196: 0.5178571428571429, 197: 0.5252431681333951, 198: 0.45927791771620485, 199: 0.36070507308684435, 200: 0.416015625, 201: 0.31994047619047616, 202: 0.11988304093567251, 203: 0.5688118811881188, 204: 0.5573487031700288, 205: 0.256034219370608, 206: 0.46179775280898877, 207: 0.3083894957006739, 208: 0.46079545454545456, 209: 0.4055859137826351, 210: 0.31934191098924275, 211: 0.3225806451612903, 212: 0.4955223880597015, 213: 0.3501221001221001, 214: 0.30121678668984353, 215: 0.3663949275362319, 216: 0.5773038842345773, 217: 0.39548772395487725, 218: 0.4376718606782768, 219: 0.4310160427807487, 220: 0.3280217644772639, 221: 0.1423913043478261, 222: 0.4514657980456026, 223: 0.38250790305584825, 224: 0.5547445255474452, 225: 0.34095707248416607, 226: 0.48481238832638474, 227: 0.47853142501555695, 228: 0.5256739409499358, 229: 0.47559366754617416, 230: 0.3403202328966521, 231: 0.48804137039431156, 232: 0.32832948421862973, 233: 0.5198902606310014, 234: 0.43886743886743884, 235: 0.3387369132049983, 236: 0.24758497316636852, 237: 0.48798328108672934, 238: 0.14861995753715498, 239: 0.46483771251931993, 240: 0.43463143254520165, 241: 0.5450867052023122, 242: 0.571917808219178, 243: 0.4846382556987116, 244: 0.5370569280343717, 245: 0.33817903596021426, 246: 0.27743526510480887, 247: 0.4913294797687861, 248: 0.30902348578491967, 249: 0.5048112509252406, 250: 0.47734222963580764, 251: 0.2583552384528727, 252: 0.45620789220404234, 253: 0.5207585853408508, 254: 0.2753935734310977, 255: 0.325903411009794, 256: 0.3595266990291262, 257: 0.3745032100275145, 258: 0.47015384615384614, 259: 0.3748246844319776, 260: 0.2241953385127636, 261: 0.46851385390428213, 262: 0.25392528424472116, 263: 0.4608788853161844, 264: 0.28976467252622623, 265: 0.49416909620991256, 266: 0.19989001924663183, 267: 0.5046428571428572, 268: 0.5138794854434665, 269: 0.49522799575821846, 270: 0.42428711897738447, 271: 0.4246100519930676, 272: 0.358337314859054, 273: 0.41170825335892514, 274: 0.3754956383822363, 275: 0.2921686746987952, 276: 0.37662337662337664, 277: 0.4748626953950148, 278: 0.0, 279: 0.46328195829555757, 280: 0.377491961414791, 281: 0.39655732380643066, 282: 0.4467382328654005, 283: 0.32150943396226417, 284: 0.42733950814436283, 285: 0.20389249304911955, 286: 0.48429676832043694, 287: 0.46412037037037035, 288: 0.39853747714808047, 289: 0.5926395939086294, 290: 0.4965108164689463, 291: 0.25940383250532295, 292: 0.4713081316290454, 293: 0.5819337267362688, 294: 0.6383442265795207, 295: 0.48641153632834166, 296: 0.5608770917484132, 297: 0.6528614457831325, 298: 0.5143380109823062, 299: 0.4763817173455728, 300: 0.5557909604519774, 301: 0.535575679172057, 302: 0.5276809910956253, 303: 0.3459409594095941, 304: 0.5933734939759037, 305: 0.49818181818181817, 306: 0.2677491244826488, 307: 0.3470460872254872, 308: 0.2597340930674264, 309: 0.43378773125608566, 310: 0.3056008700380642, 311: 0.5285497726124305, 312: 0.4944168734491315, 313: 0.5544256120527307, 314: 0.2595190380761523, 315: 0.44394762056850845, 316: 0.5295269168026101, 317: 0.47806608176218035, 318: 0.45860113421550097, 319: 0.5263157894736842, 320: 0.34602709630172096, 321: 0.24771524771524772, 322: 0.5743243243243243, 323: 0.587709497206704, 324: 0.38421528720036185, 325: 0.6484295845997974, 326: 0.6103789126853377, 327: 0.29899630216587425, 328: 0.4204119850187266, 329: 0.6542840023966447, 330: 0.4628460417678485, 331: 0.558223833257816, 332: 0.3996710526315789, 333: 0.5691666666666667, 334: 0.3810840707964602, 335: 0.481437125748503, 336: 0.48165869218500795, 337: 0.4454172366621067, 338: 0.3847814355099838, 339: 0.41204250295159384, 340: 0.31590739357729647, 341: 0.22113075747653352, 342: 0.41900452488687784, 343: 0.2259535655058043, 344: 0.29880239520958085, 345: 0.3938814531548757, 346: 0.2859237536656892, 347: 0.35384615384615387, 348: 0.642512077294686, 349: 0.4550408719346049, 350: 0.11724137931034483, 351: 0.45709828393135726, 352: 0.5741626794258373, 353: 0.22981927710843372, 354: 0.3473282442748092, 355: 0.2445414847161572, 356: 0.0, 357: 0.0, 358: 0.5117581187010078, 359: 0.4068352059925094, 360: 0.4460034013605442, 361: 0.2675893886966551, 362: 0.37485843714609285, 363: 0.4199796126401631, 364: 0.474025974025974, 365: 0.11355081555834379, 366: 0.0, 367: 0.485414235705951, 368: 0.0, 369: 0.4951267056530214, 370: 0.0, 371: 0.3719332679097154, 372: 0.3145817912657291, 373: 0.0, 374: 0.0, 375: 0.3223606168446026, 376: 0.318259385665529, 377: 0.489883507050889, 378: 0.0, 379: 0.36122448979591837, 380: 0.46065057712486884, 381: 0.43908794788273614, 382: 0.29199683042789226, 383: 0.5028924026224451, 384: 0.47593376973430884, 385: 0.6592427616926503, 386: 0.5222551928783383, 387: 0.5309734513274337, 388: 0.5175565175565175, 389: 0.17613365155131264, 390: 0.5851938895417156, 391: 0.6592252133946159, 392: 0.4481707317073171, 393: 0.520997375328084, 394: 0.23807274444969295, 395: 0.11805225653206651, 396: 0.23896103896103896, 397: 0.21439831844456123, 398: 0.3602080624187256, 399: 0.461133069828722, 400: 0.0, 401: 0.40414507772020725, 402: 0.2788703983862834, 403: 0.281079344683585, 404: 0.5290227773695811, 405: 0.3375936535918907, 406: 0.5410029498525074, 407: 0.4432081594807603, 408: 0.42613948380010985, 409: 0.5345781466113416, 410: 0.3233890214797136, 411: 0.3812636165577342, 412: 0.48586956521739133, 413: 0.0, 414: 0.37193111029681203, 415: 0.33079847908745247, 416: 0.5146327995582551, 417: 0.379746835443038, 418: 0.4254409406734367, 419: 0.44559270516717325, 420: 0.36464646464646466, 421: 0.32660869565217393, 422: 0.0, 423: 0.40711462450592883, 424: 0.5235468816291896, 425: 0.46870305458187284, 426: 0.1834388927984987, 427: 0.5003909304143862, 428: 0.28136704119850187, 429: 0.4850905218317359, 430: 0.2148000993295257, 431: 0.4577777777777778, 432: 0.5065821550463189, 433: 0.5008301051466519, 434: 0.3478747203579418, 435: 0.44130042143287174, 436: 0.553873552983081, 437: 0.4134352812670672, 438: 0.4752781211372064, 439: 0.5013360053440213, 440: 0.41262894654579557, 441: 0.38535184298707514, 442: 0.28232455258395334, 443: 0.3956146489386517, 444: 0.2563559322033898, 445: 0.5008605851979346, 446: 0.4402935290193462, 447: 0.35519591141396933, 448: 0.0, 449: 0.0, 450: 0.3612953570035115, 451: 0.41231992051664185, 452: 0.5170821791320406, 453: 0.22803149606299214, 454: 0.245406288280931, 455: 0.4451476793248945, 456: 0.5875160875160875, 457: 0.28126352228472523, 458: 0.5078577336641853, 459: 0.37488789237668163, 460: 0.24343163538873994, 461: 0.42585829072315556, 462: 0.48768834987137083, 463: 0.23043478260869565, 464: 0.40131578947368424, 465: 0.3720538720538721, 466: 0.45373939861218193, 467: 0.40933899332929047, 468: 0.28333795397837536, 469: 0.4718487394957983, 470: 0.4707543364259782, 471: 0.6777572396796057, 472: 0.5768482490272373, 473: 0.5483485873458018, 474: 0.3256333830104322, 475: 0.5308361710177828, 476: 0.3442455242966752, 477: 0.49257425742574257, 478: 0.42830609212481424, 479: 0.30416248746238717, 480: 0.4419035846724351, 481: 0.2840321654221712, 482: 0.5344931013797241, 483: 0.37722772277227723, 484: 0.5642965204236006, 485: 0.5890097309673726, 486: 0.45296007342817807, 487: 0.42786069651741293, 488: 0.4506132989025178, 489: 0.5213414634146342, 490: 0.38082996694821886, 491: 0.17256740914419696, 492: 0.6129196337741607, 493: 0.6271186440677966, 494: 0.4733009708737864, 495: 0.35184067592033796, 496: 0.22594646732577767, 497: 0.4820770519262982, 498: 0.29849424269264835, 499: 0.4294917680744452, 500: 0.6138049058756417, 501: 0.4946808510638298, 502: 0.5292259083728278, 503: 0.0, 504: 0.13756613756613756, 505: 0.5318302387267905, 506: 0.4046035805626598, 507: 0.6272727272727273, 508: 0.4158636026686434, 509: 0.4638939670932358, 510: 0.4956521739130435, 511: 0.4792746113989637, 512: 0.0, 513: 0.5218120805369127, 514: 0.29451540195341847, 515: 0.4319643740722415, 516: 0.3066914498141264, 517: 0.4645161290322581, 518: 0.3185063152114223, 519: 0.2918127448958548, 520: 0.45768025078369906, 521: 0.6474025974025974, 522: 0.41840607210626185, 523: 0.5713432835820895, 524: 0.1977704376548307, 525: 0.40648567119155354, 526: 0.5133189344852411, 527: 0.598479612992398, 528: 0.41739824421388666, 529: 0.4713804713804714, 530: 0.4034134988363072, 531: 0.2953315290933694, 532: 0.282703488372093, 533: 0.5684673366834171, 534: 0.2902601591055687, 535: 0.5696804894629504, 536: 0.5978618421052632, 537: 0.5622161671207992, 538: 0.4229534510433387, 539: 0.4137884872824632, 540: 0.10579541034616881, 541: 0.28609201480698043, 542: 0.464326160815402, 543: 0.2482701356213673, 544: 0.5004557885141294, 545: 0.5866171003717472, 546: 0.291497975708502, 547: 0.2777268560953254, 548: 0.5271523178807948, 549: 0.33284529038555394, 550: 0.3304050756466569, 551: 0.5267520723436323, 552: 0.3783231083844581, 553: 0.3043859649122807, 554: 0.3857677902621723, 555: 0.4996446339729922, 556: 0.5569007263922519, 557: 0.4996237772761475, 558: 0.45811051693404636, 559: 0.552297165200391, 560: 0.5875816993464053, 561: 0.45657015590200445, 562: 0.27101200686106347, 563: 0.14581328200192492, 564: 0.5372168284789643, 565: 0.6630525437864887, 566: 0.6020971302428256, 567: 0.4263233190271817, 568: 0.4745098039215686, 569: 0.33964879852125696, 570: 0.1962730403078793, 571: 0.35608082348455966, 572: 0.6235190873189995, 573: 0.44082081348479296, 574: 0.3860010293360782, 575: 0.43371757925072046, 576: 0.48933957358294333, 577: 0.37010309278350517, 578: 0.27944280287040946, 579: 0.5428764348413234, 580: 0.44256455921638466, 581: 0.4067140090380891, 582: 0.24449877750611246, 583: 0.219435736677116, 584: 0.4052494415487714, 585: 0.404392072844135, 586: 0.3493282149712092, 587: 0.30613668061366806, 588: 0.4479945615227736, 589: 0.3892741562644475, 590: 0.32589285714285715, 591: 0.5950255102040817, 592: 0.5853658536585366, 593: 0.4957932692307692, 594: 0.4493783303730018, 595: 0.48223733938019653, 596: 0.5213494992092778, 597: 0.24380165289256198, 598: 0.5431286549707602, 599: 0.31478199220134706, 600: 0.4888888888888889, 601: 0.5862068965517241, 602: 0.5227803738317757, 603: 0.5537190082644629, 604: 0.43121019108280256, 605: 0.5051020408163265, 606: 0.4544378698224852, 607: 0.5395833333333333, 608: 0.6354790419161677, 609: 0.5986733001658375, 610: 0.4584805653710247, 611: 0.5684615384615385, 612: 0.4744557974233674, 613: 0.6620689655172414, 614: 0.47658979734451434, 615: 0.4700944386149003, 616: 0.3293718166383701, 617: 0.5852734163508392, 618: 0.5655042412818096, 619: 0.3143093465674111, 620: 0.5271966527196653, 621: 0.47, 622: 0.32494608195542773, 623: 0.6522506619593998, 624: 0.4892703862660944, 625: 0.5982367758186398, 626: 0.7432517263025737, 627: 0.47337278106508873, 628: 0.6659167604049494, 629: 0.5756232686980609, 630: 0.5671566142929549, 631: 0.4802784222737819, 632: 0.46223736513344693, 633: 0.5706959706959707, 634: 0.26216216216216215, 635: 0.5162744116174262, 636: 0.5198473282442748, 637: 0.31198808637379, 638: 0.6284271284271284, 639: 0.5724838411819021, 640: 0.6593337523570082, 641: 0.5228668941979522, 642: 0.5282660332541568, 643: 0.6488824801730353, 644: 0.6532385466034755, 645: 0.5498199279711885, 646: 0.5869041887337506, 647: 0.35675876135731505, 648: 0.19386126457949662, 649: 0.5139225181598063, 650: 0.6337805840568271, 651: 0.523407521105142, 652: 0.33314054366685947, 653: 0.1881720430107527, 654: 0.5959468017732742, 655: 0.36061381074168797, 656: 0.3437801350048216, 657: 0.3076557299096529, 658: 0.20042194092827004, 659: 0.4594348222424795, 660: 0.4423407917383821, 661: 0.27942353883106485, 662: 0.4861804861804862, 663: 0.3657211828605914, 664: 0.5094339622641509, 665: 0.45305980528511824, 666: 0.4166059723233795, 667: 0.5045537340619308, 668: 0.3704379562043796, 669: 0.500459981600736, 670: 0.5233751425313569, 671: 0.0, 672: 0.42899702085402186, 673: 0.323406789755807, 674: 0.05649484536082474, 675: 0.35842293906810035, 676: 0.36201117318435755, 677: 0.25877886744701045, 678: 0.43204202232435984, 679: 0.15428354814253223, 680: 0.2585139318885449, 681: 0.38872043662825956, 682: 0.17408965617292907, 683: 0.35688005886681384, 684: 0.22180293501048218, 685: 0.337, 686: 0.3822033898305085, 687: 0.3045789043336059, 688: 0.3584993052339046, 689: 0.2111111111111111, 690: 0.44181646168401134, 691: 0.3457350272232305, 692: 0.3733826247689464, 693: 0.24049513704686118, 694: 0.38465274405051, 695: 0.2804259634888438, 696: 0.41453245979749853, 697: 0.33405639913232105, 698: 0.48080949057920447, 699: 0.3443616029822926, 700: 0.28982456140350876, 701: 0.34091923248549755, 702: 0.3016759776536313, 703: 0.6311200536552649, 704: 0.5298982188295165, 705: 0.21858700806069228, 706: 0.2671849427168576, 707: 0.4361861861861862, 708: 0.5057692307692307, 709: 0.3878007834359261, 710: 0.3706896551724138, 711: 0.22848200312989045, 712: 0.34566403881140084, 713: 0.437946718648473, 714: 0.4960212201591512, 715: 0.42193486590038315, 716: 0.38730723606168443, 717: 0.1461187214611872, 718: 0.2703768624014023, 719: 0.2920729122509538, 720: 0.5150442477876106, 721: 0.32383040935672514, 722: 0.23685413808870598, 723: 0.0, 724: 0.2610050642773666, 725: 0.1436233611442193, 726: 0.2981871994080651, 727: 0.3878954607977992, 728: 0.3247863247863248, 729: 0.18360433604336043, 730: 0.4983563445101907, 731: 0.33952125061064975, 732: 0.3192327903310562, 733: 0.4152646696758309, 734: 0.4598393574297189, 735: 0.2451550387596899, 736: 0.5516834022445364, 737: 0.41073384446878425, 738: 0.0, 739: 0.28836206896551725, 740: 0.5466970387243736, 741: 0.34214463840399, 742: 0.529275092936803, 743: 0.5625479662317728, 744: 0.4938716654650324, 745: 0.2820770519262982, 746: 0.3720657276995305, 747: 0.5713058419243986, 748: 0.31543887147335425, 749: 0.46970684039087945, 750: 0.44963738920225627, 751: 0.5384164222873901, 752: 0.3113933795227098, 753: 0.1942270058708415, 754: 0.49955985915492956, 755: 0.31649189704480457, 756: 0.6409214092140921, 757: 0.4078740157480315, 758: 0.30298369732390035, 759: 0.5398119122257053, 760: 0.5770925110132159, 761: 0.5692857142857143, 762: 0.6033013844515442, 763: 0.5099925980754997, 764: 0.508177570093458, 765: 0.4354260089686099, 766: 0.30420353982300885, 767: 0.447870778267254, 768: 0.4888888888888889, 769: 0.27843986998916576, 770: 0.5070652173913044, 771: 0.39226973684210525, 772: 0.3916540975364505, 773: 0.4966517857142857, 774: 0.42083333333333334, 775: 0.4009756097560976, 776: 0.2741585233441911, 777: 0.5041379310344828, 778: 0.3736434108527132, 779: 0.4016042780748663, 780: 0.47839318320146074, 781: 0.304986642920748, 782: 0.6192364898363907, 783: 0.5018115942028986, 784: 0.49527027027027026, 785: 0.6243822075782537, 786: 0.470299727520436, 787: 0.11799474605954466, 788: 0.5660377358490566, 789: 0.41003948110547095, 790: 0.5414078674948241, 791: 0.5757250268528464, 792: 0.5206489675516224, 793: 0.4357308584686775, 794: 0.4076124567474048, 795: 0.30393145161290325, 796: 0.4368932038834951, 797: 0.23234524847428073, 798: 0.4994675186368477, 799: 0.6302521008403361, 

Computing centroid accuracy: 100%|██████████| 12793/12793 [00:04<00:00, 3078.77cell/s]

{'true_positives': 11350, 'false_negatives': 1443, 'false_positives': 1354, 'merged_cells': 2038, 'precision': 0.8934193954659949, 'recall': 0.8872039396544985, 'f1': 0.8903008197042789, 'voxel_dice': 0.5711498987531696, 'iou_3d': 0.3997269540414196, 'per_cell_iou': {1: 0.23710482529118138, 2: 0.4166168559473999, 3: 0.25673364685763145, 4: 0.0, 5: 0.18575667655786351, 6: 0.27456258411843876, 7: 0.08392390898918314, 8: 0.2526080476900149, 9: 0.019686800894854587, 10: 0.25142495250158325, 11: 0.4362017804154303, 12: 0.20499021526418787, 13: 0.0660321237358715, 14: 0.18805657412257726, 15: 0.19118279569892474, 16: 0.01809954751131222, 17: 0.0, 18: 0.0, 19: 0.3341875961045618, 20: 0.0, 21: 0.1763911399243652, 22: 0.07029015120555783, 23: 0.0, 24: 0.18495934959349594, 25: 0.20704467353951891, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.09558823529411764, 32: 0.042986425339366516, 33: 0.0, 34: 0.0, 35: 0.06429070580013976, 36: 0.35994677312042583, 37: 0.0, 38: 0.023476523476523476, 39: 0.0, 40: 0.0, 41: 0.01156326439848788, 42: 0.21586424625098657, 43: 0.11175560711523588, 44: 0.30644454186760195, 45: 0.112969390975071, 46: 0.18257756563245822, 47: 0.3426237385872177, 48: 0.1969209947555405, 49: 0.253259779338014, 50: 0.2233128834355828, 51: 0.1125, 52: 0.4870940882597835, 53: 0.32246039142590865, 54: 0.3489531405782652, 55: 0.0, 56: 0.0, 57: 0.25204200700116686, 58: 0.1313497822931785, 59: 0.12730434782608696, 60: 0.27459016393442626, 61: 0.13045226130653267, 62: 0.030392156862745098, 63: 0.16177596325593263, 64: 0.0, 65: 0.18861423220973783, 66: 0.023600439077936335, 67: 0.2512892639474918, 68: 0.35145964510589583, 69: 0.0, 70: 0.059295330850759095, 71: 0.13722943722943723, 72: 0.07592110160029773, 73: 0.34245960502692996, 74: 0.38608695652173913, 75: 0.2857142857142857, 76: 0.4088013896931094, 77: 0.3451443569553806, 78: 0.3765836609873307, 79: 0.29315427448411396, 80: 0.06059152677857714, 81: 0.3284923928077455, 82: 0.14831349206349206, 83: 0.15639097744360902, 84: 0.0, 85: 0.48980496453900707, 86: 0.1533226581265012, 87: 0.25617732558139533, 88: 0.48142333856619574, 89: 0.3235668789808917, 90: 0.1677750906892382, 91: 0.32669537136706134, 92: 0.0, 93: 0.08058608058608059, 94: 0.017189514396218308, 95: 0.33079526226734346, 96: 0.34164871300600974, 97: 0.0, 98: 0.056910569105691054, 99: 0.0, 100: 0.20923219670610066, 101: 0.24807903402854006, 102: 0.19333843797856048, 103: 0.06275659824046921, 104: 0.0, 105: 0.0, 106: 0.0, 107: 0.0, 108: 0.10959715639810426, 109: 0.0177717019822283, 110: 0.26025236593059936, 111: 0.3435700575815739, 112: 0.4280279010779962, 113: 0.14984709480122324, 114: 0.3302540415704388, 115: 0.25734024179620035, 116: 0.44181925575900766, 117: 0.3776842105263158, 118: 0.1539434837621257, 119: 0.18211430263547526, 120: 0.2262472885032538, 121: 0.022888283378746595, 122: 0.1850079744816587, 123: 0.0, 124: 0.0891566265060241, 125: 0.4034729315628192, 126: 0.28635437881873727, 127: 0.05794449527294907, 128: 0.023097311624384703, 129: 0.10608203677510608, 130: 0.0, 131: 0.32418952618453867, 132: 0.07350862312694374, 133: 0.16562650024003842, 134: 0.44980587909040487, 135: 0.11921793037672866, 136: 0.360447381799695, 137: 0.0, 138: 0.0, 139: 0.4103139013452915, 140: 0.3341078066914498, 141: 0.10263884627186254, 142: 0.2064400130761687, 143: 0.33238636363636365, 144: 0.20738327904451684, 145: 0.027588964414234307, 146: 0.03666841278156103, 147: 0.382339343504392, 148: 0.5492537313432836, 149: 0.06672760511882998, 150: 0.2261029411764706, 151: 0.0366051182377713, 152: 0.4039344262295082, 153: 0.1110494169905608, 154: 0.14609258337481335, 155: 0.3740803621958121, 156: 0.11164274322169059, 157: 0.04287983059820011, 158: 0.4384564204923486, 159: 0.2748671222475323, 160: 0.30643513789581206, 161: 0.2717864923747277, 162: 0.32954545454545453, 163: 0.05943627450980392, 164: 0.11533923303834809, 165: 0.6077558804831532, 166: 0.5215258855585831, 167: 0.0, 168: 0.0, 169: 0.4039955604883463, 170: 0.0, 171: 0.2912371134020619, 172: 0.6077510275983559, 173: 0.41715312079030087, 174: 0.29656203288490285, 175: 0.2599645704162976, 176: 0.383022170361727, 177: 0.1971706454465075, 178: 0.3681267474370923, 179: 0.2565217391304348, 180: 0.16704545454545455, 181: 0.0, 182: 0.0, 183: 0.16845425867507888, 184: 0.23675181090354555, 185: 0.08411214953271028, 186: 0.1600143833153542, 187: 0.0, 188: 0.0, 189: 0.023713826366559485, 190: 0.4134253450439147, 191: 0.1631711409395973, 192: 0.30816170861937453, 193: 0.017533252720677146, 194: 0.23468426013195098, 195: 0.20672268907563024, 196: 0.15317286652078774, 197: 0.0, 198: 0.06654991243432574, 199: 0.0, 200: 0.0, 201: 0.0, 202: 0.0, 203: 0.3716455696202532, 204: 0.4744437763078773, 205: 0.23277527366387638, 206: 0.0, 207: 0.02974668835696026, 208: 0.20680796403339757, 209: 0.0, 210: 0.0, 211: 0.0, 212: 0.313468992248062, 213: 0.04603992273019961, 214: 0.0, 215: 0.0, 216: 0.11365494685200327, 217: 0.022792022792022793, 218: 0.0, 219: 0.0, 220: 0.0, 221: 0.0, 222: 0.1341789052069426, 223: 0.183920704845815, 224: 0.4198800342759212, 225: 0.0, 226: 0.18556701030927836, 227: 0.17658108954289292, 228: 0.33649932157394846, 229: 0.20609065155807366, 230: 0.04167881084232002, 231: 0.2536764705882353, 232: 0.08464655560558307, 233: 0.0, 234: 0.02730528200537153, 235: 0.0, 236: 0.0, 237: 0.0, 238: 0.0, 239: 0.0, 240: 0.0, 241: 0.13558318531675548, 242: 0.18252933507170796, 243: 0.0, 244: 0.22441160372194854, 245: 0.2111706197398623, 246: 0.0, 247: 0.0, 248: 0.0, 249: 0.031538461538461536, 250: 0.1427369601794728, 251: 0.0, 252: 0.26524685382381413, 253: 0.2211186617877679, 254: 0.0, 255: 0.0, 256: 0.0, 257: 0.0, 258: 0.0, 259: 0.0, 260: 0.0, 261: 0.0, 262: 0.0, 263: 0.1468189233278956, 264: 0.0, 265: 0.1772945079248065, 266: 0.0, 267: 0.08238851095993953, 268: 0.1580909768829232, 269: 0.4146341463414634, 270: 0.3292867981790592, 271: 0.1138353765323993, 272: 0.25809716599190285, 273: 0.23258049014896684, 274: 0.10020964360587002, 275: 0.05970149253731343, 276: 0.08454106280193237, 277: 0.0, 278: 0.0, 279: 0.0, 280: 0.016883116883116882, 281: 0.05623552762156798, 282: 0.11230388109000826, 283: 0.0, 284: 0.2008301404853129, 285: 0.0, 286: 0.09771986970684039, 287: 0.0, 288: 0.0, 289: 0.16137394685677253, 290: 0.33824613117170227, 291: 0.3152289669861555, 292: 0.3148301574150787, 293: 0.5573065902578797, 294: 0.4490106544901065, 295: 0.33184731122875455, 296: 0.3773274917853231, 297: 0.4578025477707006, 298: 0.29699738903394257, 299: 0.3791907514450867, 300: 0.26949280847842544, 301: 0.31593038821954483, 302: 0.4198295894655306, 303: 0.0, 304: 0.4868421052631579, 305: 0.20667330677290838, 306: 0.0390987408880053, 307: 0.0, 308: 0.0, 309: 0.03148057058534186, 310: 0.0, 311: 0.1874659400544959, 312: 0.0, 313: 0.4747378455672069, 314: 0.1345224823485693, 315: 0.21411843425894947, 316: 0.5316698656429942, 317: 0.33054559936280364, 318: 0.13353500432152118, 319: 0.35260115606936415, 320: 0.0, 321: 0.20504807692307692, 322: 0.5047619047619047, 323: 0.5136761487964989, 324: 0.2602398732744965, 325: 0.569023569023569, 326: 0.4400749063670412, 327: 0.12805526036131776, 328: 0.44795405599425697, 329: 0.5294871794871795, 330: 0.23795330352707403, 331: 0.4336569579288026, 332: 0.3179587831207066, 333: 0.4331150608044902, 334: 0.21298495645288995, 335: 0.4191304347826087, 336: 0.33403805496828753, 337: 0.2140105078809107, 338: 0.1578662334145681, 339: 0.3203378817413905, 340: 0.30007501875468867, 341: 0.2595102754700481, 342: 0.24360189573459715, 343: 0.0, 344: 0.0, 345: 0.0, 346: 0.0, 347: 0.4159178433889602, 348: 0.0, 349: 0.0, 350: 0.0, 351: 0.0, 352: 0.0, 353: 0.0, 354: 0.0, 355: 0.0, 356: 0.0, 357: 0.0, 358: 0.0, 359: 0.0, 360: 0.0, 361: 0.0, 362: 0.0, 363: 0.0, 364: 0.0, 365: 0.0, 366: 0.0, 367: 0.0, 368: 0.0, 369: 0.0, 370: 0.0, 371: 0.0, 372: 0.0, 373: 0.0, 374: 0.0, 375: 0.0, 376: 0.10078387458006718, 377: 0.0, 378: 0.0, 379: 0.0, 380: 0.0, 381: 0.0, 382: 0.0, 383: 0.1685872812633376, 384: 0.15710328452710723, 385: 0.030439684329199548, 386: 0.02967359050445104, 387: 0.10758776896942242, 388: 0.0, 389: 0.0, 390: 0.0, 391: 0.21862348178137653, 392: 0.0, 393: 0.0, 394: 0.0, 395: 0.0, 396: 0.0, 397: 0.0, 398: 0.0, 399: 0.0, 400: 0.0, 401: 0.0, 402: 0.13783323879750425, 403: 0.0, 404: 0.2770700636942675, 405: 0.058797524314765696, 406: 0.3986731001206273, 407: 0.15266106442577032, 408: 0.0, 409: 0.11768826619964974, 410: 0.0, 411: 0.13515537251965556, 412: 0.0, 413: 0.0, 414: 0.0, 415: 0.0, 416: 0.0, 417: 0.0, 418: 0.0, 419: 0.0, 420: 0.0, 421: 0.0, 422: 0.0, 423: 0.0, 424: 0.0, 425: 0.20161697827185449, 426: 0.0, 427: 0.19669277632724108, 428: 0.0, 429: 0.0, 430: 0.0, 431: 0.010180623973727421, 432: 0.0, 433: 0.0, 434: 0.0, 435: 0.21841541755888652, 436: 0.0, 437: 0.04155124653739612, 438: 0.109717868338558, 439: 0.18635724331926865, 440: 0.010379500486539085, 441: 0.0, 442: 0.0, 443: 0.0, 444: 0.0, 445: 0.18725868725868725, 446: 0.17202692595362754, 447: 0.04219948849104859, 448: 0.0, 449: 0.21207893163244967, 450: 0.1295315682281059, 451: 0.1746592629984856, 452: 0.0640495867768595, 453: 0.048657187993680885, 454: 0.016741527153940384, 455: 0.0413135593220339, 456: 0.4530612244897959, 457: 0.012652507907817443, 458: 0.06813417190775681, 459: 0.17884517118037813, 460: 0.06779661016949153, 461: 0.0, 462: 0.10855872545387181, 463: 0.0, 464: 0.3235893949694086, 465: 0.3750724637681159, 466: 0.3001027749229188, 467: 0.22799874725963043, 468: 0.23642081189251002, 469: 0.22217068645640073, 470: 0.19749835418038184, 471: 0.5347798340778558, 472: 0.26487252124645894, 473: 0.44, 474: 0.26488018551919607, 475: 0.18959257765227913, 476: 0.16507042253521126, 477: 0.08599382080329557, 478: 0.05249569707401033, 479: 0.0, 480: 0.053212199870214145, 481: 0.17852941176470588, 482: 0.2735166425470333, 483: 0.08026030368763558, 484: 0.44224598930481285, 485: 0.26704795424549055, 486: 0.0, 487: 0.0, 488: 0.0, 489: 0.26386645126548197, 490: 0.2550532892319, 491: 0.1564599731234402, 492: 0.3294429708222812, 493: 0.04699140401146132, 494: 0.1263001485884101, 495: 0.0, 496: 0.0, 497: 0.0, 498: 0.43511871893981224, 499: 0.3101983002832861, 500: 0.37218045112781956, 501: 0.4592476489028213, 502: 0.0857843137254902, 503: 0.0, 504: 0.026701119724375538, 505: 0.26400273224043713, 506: 0.1939443535188216, 507: 0.4381720430107527, 508: 0.09377738825591586, 509: 0.19334619093539054, 510: 0.11186440677966102, 511: 0.31971465629053175, 512: 0.0, 513: 0.0, 514: 0.0, 515: 0.32082551594746717, 516: 0.0, 517: 0.12381516587677725, 518: 0.0, 519: 0.48497409326424873, 520: 0.358695652173913, 521: 0.5571979434447301, 522: 0.23584229390681002, 523: 0.46131639722863743, 524: 0.0, 525: 0.0, 526: 0.28314606741573034, 527: 0.3525329632199861, 528: 0.08220271348762968, 529: 0.22822174226061914, 530: 0.25077639751552794, 531: 0.13125845737483086, 532: 0.09229651162790697, 533: 0.34232498394348104, 534: 0.2721995269834444, 535: 0.47918088737201364, 536: 0.4792358803986711, 537: 0.5344352617079889, 538: 0.18770491803278688, 539: 0.2930988184747583, 540: 0.34837287696097496, 541: 0.3516803387139455, 542: 0.43591160220994474, 543: 0.22102052135330005, 544: 0.20564149226569609, 545: 0.5206301575393848, 546: 0.038461538461538464, 547: 0.056338028169014086, 548: 0.4782308223911541, 549: 0.19960956564177648, 550: 0.24948979591836734, 551: 0.24420401854714066, 552: 0.3399182561307902, 553: 0.20877192982456141, 554: 0.0, 555: 0.4407158836689038, 556: 0.399673735725938, 557: 0.4908116385911179, 558: 0.29739776951672864, 559: 0.4532803180914513, 560: 0.6085753803596127, 561: 0.3818386914833615, 562: 0.24627923458540044, 563: 0.21246612466124662, 564: 0.3889845094664372, 565: 0.5471854304635762, 566: 0.22972972972972974, 567: 0.2840909090909091, 568: 0.39952718676122934, 569: 0.133086876155268, 570: 0.0727938186254575, 571: 0.05561904761904762, 572: 0.5401968826907301, 573: 0.21066666666666667, 574: 0.12377514182568335, 575: 0.1746031746031746, 576: 0.18444561219127692, 577: 0.0, 578: 0.0, 579: 0.29659763313609466, 580: 0.2465753424657534, 581: 0.15701415701415702, 582: 0.0, 583: 0.0, 584: 0.22167111789393362, 585: 0.10444563470808785, 586: 0.0, 587: 0.1499302649930265, 588: 0.1994459833795014, 589: 0.3067343173431734, 590: 0.1037593984962406, 591: 0.4824509220701963, 592: 0.48069603045133225, 593: 0.3161057692307692, 594: 0.20926090828138913, 595: 0.3116679718089272, 596: 0.5751047277079593, 597: 0.18898071625344354, 598: 0.4095163806552262, 599: 0.23345323741007193, 600: 0.40481927710843374, 601: 0.3069526627218935, 602: 0.4632768361581921, 603: 0.32519422863485015, 604: 0.39223057644110276, 605: 0.4128686327077748, 606: 0.3325349301397206, 607: 0.3953488372093023, 608: 0.5023622047244094, 609: 0.495985727029438, 610: 0.46631205673758863, 611: 0.4625187406296852, 612: 0.42611380679311867, 613: 0.5008038585209004, 614: 0.24005681818181818, 615: 0.37758433079434167, 616: 0.3832167832167832, 617: 0.4828962371721779, 618: 0.2950152594099695, 619: 0.36266739546324134, 620: 0.4818688981868898, 621: 0.06037735849056604, 622: 0.1627069834413247, 623: 0.17216117216117216, 624: 0.2586352148272957, 625: 0.5308720560152769, 626: 0.6285370258880193, 627: 0.3822854520422212, 628: 0.6275743707093822, 629: 0.4075963718820862, 630: 0.39533705017739484, 631: 0.31709646609360076, 632: 0.2930591259640103, 633: 0.25206301575393847, 634: 0.1837471783295711, 635: 0.21648963075366717, 636: 0.15873015873015872, 637: 0.17213712618526622, 638: 0.5318840579710145, 639: 0.5440366972477064, 640: 0.6934487021013597, 641: 0.5187207488299532, 642: 0.403855421686747, 643: 0.6131541725601132, 644: 0.6442845723421263, 645: 0.4355140186915888, 646: 0.4950445986124876, 647: 0.35569219303148875, 648: 0.4136999754480727, 649: 0.29743589743589743, 650: 0.5429936305732485, 651: 0.3998416468725257, 652: 0.0, 653: 0.0, 654: 0.33155792276964047, 655: 0.05425032037590773, 656: 0.0, 657: 0.0, 658: 0.0, 659: 0.0, 660: 0.0, 661: 0.0, 662: 0.0, 663: 0.0, 664: 0.0, 665: 0.0, 666: 0.0, 667: 0.0, 668: 0.0, 669: 0.0, 670: 0.0, 671: 0.0, 672: 0.3545183714001986, 673: 0.19467728415758592, 674: 0.11959654178674352, 675: 0.0896700143472023, 676: 0.0, 677: 0.11958241062954761, 678: 0.2894211576846307, 679: 0.11317535545023696, 680: 0.0, 681: 0.13108614232209737, 682: 0.3126089482858803, 683: 0.09774436090225563, 684: 0.14932337844143723, 685: 0.16021505376344086, 686: 0.05847457627118644, 687: 0.0, 688: 0.1000463177396943, 689: 0.0, 690: 0.0, 691: 0.10088743577767398, 692: 0.010175763182238668, 693: 0.0, 694: 0.0, 695: 0.0, 696: 0.12674418604651164, 697: 0.21372328458942633, 698: 0.36711711711711714, 699: 0.12114125350795135, 700: 0.1316901408450704, 701: 0.14457831325301204, 702: 0.1779728651237031, 703: 0.6223146223146223, 704: 0.37270341207349084, 705: 0.24511672224868986, 706: 0.07692307692307693, 707: 0.11036036036036036, 708: 0.2459639126305793, 709: 0.0, 710: 0.0, 711: 0.0, 712: 0.22713864306784662, 713: 0.1738562091503268, 714: 0.24234354194407456, 715: 0.14776056927584763, 716: 0.0, 717: 0.0, 718: 0.046228710462287104, 719: 0.1793779292714103, 720: 0.0, 721: 0.0, 722: 0.03468208092485549, 723: 0.0, 724: 0.0, 725: 0.0, 726: 0.0, 727: 0.0, 728: 0.0, 729: 0.0, 730: 0.0786056049213944, 731: 0.0, 732: 0.09158679446219382, 733: 0.0, 734: 0.0, 735: 0.11071428571428571, 736: 0.0, 737: 0.02592388306674021, 738: 0.0, 739: 0.0, 740: 0.45423023578363386, 741: 0.15369127516778525, 742: 0.379441023211748, 743: 0.16413623307345096, 744: 0.08936651583710407, 745: 0.07420814479638009, 746: 0.14756003098373355, 747: 0.4423676012461059, 748: 0.03253968253968254, 749: 0.0, 750: 0.2642736009044658, 751: 0.2116741500962155, 752: 0.07585385226370135, 753: 0.10962633011630785, 754: 0.3371192565823438, 755: 0.16249451032059728, 756: 0.46506211180124224, 757: 0.2927063339731286, 758: 0.07545909849749582, 759: 0.4736371760500447, 760: 0.33852335509794074, 761: 0.37888446215139443, 762: 0.4057266342517558, 763: 0.15198059822150364, 764: 0.3048469387755102, 765: 0.24699907663896584, 766: 0.3306152705707932, 767: 0.3464544138929088, 768: 0.2910094637223975, 769: 0.0, 770: 0.047731290512669416, 771: 0.07339449541284404, 772: 0.0, 773: 0.41791817711030554, 774: 0.3444213444213444, 775: 0.1261730969760167, 776: 0.0, 777: 0.09805335255948089, 778: 0.2807142857142857, 779: 0.4214046822742475, 780: 0.340878828229028, 781: 0.19217570350034316, 782: 0.41043652784746615, 783: 0.32425892316999394, 784: 0.15621215790748366, 785: 0.5346051464063887, 786: 0.27563025210084036, 787: 0.0, 788: 0.09480337078651685, 789: 0.323668950975224, 790: 0.220703125, 791: 0.4171678512848551, 792: 0.06909361069836553, 793: 0.1228600201409869, 794: 0.0, 795: 0.0, 796: 0.20082582582582584, 797: 0.39763313609467454, 798: 0.26889375684556405, 799: 0.534711964549483, 800: 0.5404109589041096, 801: 0.39326334208223973, 802: 0.30425963488843816, 803: 0.0, 804: 0.21846553966189858, 805: 0.1918075422626788, 806: 0.36087153881071266, 807: 0.17717391304347826, 808: 0.31188423645320196, 809: 0.0, 810: 0.19754552652414886, 811: 0.07853159851301116, 812: 0.4118143459915612, 813: 0.35843137254901963, 814: 0.02177700348432056, 815: 0.13088029809035864, 816: 0.1427627230667548, 817: 0.0, 818: 0.0, 819: 0.3908086925543285, 820: 0.591246290801187, 821: 0.09129213483146068, 822: 0.3275313097007005, 823: 0.4675245098039216, 824: 0.44360189573459713, 825: 0.4978540772532189, 826: 0.3305, 827: 0.22226198997852542, 828: 0.3788049605411499, 829: 0.19961704164672092, 830: 0.5240061951471348, 831: 0.0, 832: 0.271461716937355, 833: 0.2123015873015873, 834: 0.2748324192565509, 835: 0.44477836213373406, 836: 0.5416666666666666, 837: 0.0, 838: 0.3556058890147225, 839: 0.26584022038567495, 840: 0.0, 841: 0.26694166175604006, 842: 0.20185728250244378, 843: 0.3787047200878156, 844: 0.14587485053806298, 845: 0.29289810322011467, 846: 0.6343825665859564, 847: 0.4611673902556681, 848: 0.6040302267002519, 849: 0.3399390243902439, 850: 0.0, 851: 0.0, 852: 0.45963172804532576, 853: 0.48243114909781576, 854: 0.41713961407491484, 855: 0.2511415525114155, 856: 0.23023351085620647, 857: 0.3227320125130344, 858: 0.22910721565430087, 859: 0.5895166780122533, 860: 0.2578864353312303, 861: 0.10473235065942592, 862: 0.31289398280802294, 863: 0.459378733572282, 864: 0.547945205479452, 865: 0.41858325666973323, 866: 0.6012354152367879, 867: 0.45112781954887216, 868: 0.31288766368022053, 869: 0.2836919592298981, 870: 0.27270924236414124, 871: 0.28251912889935255, 872: 0.18424962852897475, 873: 0.14002428166734115, 874: 0.31755239520958084, 875: 0.2159973000337496, 876: 0.2247191011235955, 877: 0.0, 878: 0.38425492033739456, 879: 0.5752212389380531, 880: 0.46812470916705445, 881: 0.4525350593311758, 882: 0.2892873997168476, 883: 0.42405391394504927, 884: 0.22631094756209752, 885: 0.0, 886: 0.26722222222222225, 887: 0.37411461687057307, 888: 0.1275890637945319, 889: 0.15256980979360582, 890: 0.2402315484804631, 891: 0.39019476158495636, 892: 0.03964321110009911, 893: 0.0, 894: 0.0, 895: 0.25130172650041105, 896: 0.46149323927101704, 897: 0.38429368029739774, 898: 0.25504151838671413, 899: 0.5484927916120577, 900: 0.0, 901: 0.09133405249910104, 902: 0.42027690933452433, 903: 0.285572632622707, 904: 0.1700721153846154, 905: 0.4869857262804366, 906: 0.21053614795441808, 907: 0.4272463768115942, 908: 0.3683206106870229, 909: 0.45098039215686275, 910: 0.5689479060265578, 911: 0.0, 912: 0.39143825069294735, 913: 0.2600297176820208, 914: 0.27609811751283514, 915: 0.3838383838383838, 916: 0.10248552945182159, 917: 0.0651372388365424, 918: 0.448471615720524, 919: 0.44017094017094016, 920: 0.258493353028065, 921: 0.3902686264571718, 922: 0.368921185019564, 923: 0.2480037576326914, 924: 0.4591321897073663, 925: 0.20829458806025664, 926: 0.4810978767477991, 927: 0.27835051546391754, 928: 0.33171521035598706, 929: 0.232461355529132, 930: 0.25145819831497085, 931: 0.27812370278123705, 932: 0.44887568943572337, 933: 0.35778443113772457, 934: 0.4968152866242038, 935: 0.500609756097561, 936: 0.18582791033984092, 937: 0.5198910081

In [26]:
mean_iou_suijkerbuijk = np.mean(list(results_suijkerbuijk["per_cell_iou"].values()))
print(f"Mean IoU Suijkerbuijk: {mean_iou_suijkerbuijk:.3f}")
mean_iou_cp4 = np.mean(list(results_cp4["per_cell_iou"].values()))
print(f"Mean IoU CP4: {mean_iou_cp4:.3f}")

Mean IoU Suijkerbuijk: 0.602
Mean IoU CP4: 0.603

In [28]:
# Training fruitfly model

training_dir = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1\model"


input_directory = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1"
image = tifffile.imread(os.path.join(input_directory, f"data.tif"))
segmentation = tifffile.imread(os.path.join(input_directory, f"GroundTruth.tif"))
count = 0
# select 5 random integers between 0 and esg.shape[0]-1
selected_slices = np.random.choice(segmentation.shape[0], size=20, replace=False)
for slice in selected_slices:
    if count >= 7:
        break
    if len(np.unique(segmentation[slice, :, :])) < 5:
        continue
    count += 1
    tifffile.imwrite(
        os.path.join(training_dir, f"slice_{slice}_img.tif"),
        image[slice, :, :],
        imagej=True,
    )
    tifffile.imwrite(
        os.path.join(training_dir, f"slice_{slice}_mask.tif"),
        segmentation[slice, :, :],
        imagej=True,
    )

In [29]:
from cellpose import io, models, train

io.logger_setup()

training_dir = r"C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1\model"


output = io.load_train_test_data(
    training_dir,
    image_filter="_img",
    mask_filter="_mask",
    look_one_level_down=False,
)
images, labels, image_names, test_images, test_labels, image_names_test = output

model = models.CellposeModel(gpu=True)

model_path, train_losses, test_losses = train.train_seg(
    model.net,
    train_data=images,
    train_labels=labels,
    test_data=test_images,
    test_labels=test_labels,
    weight_decay=0.1,
    learning_rate=1e-5,
    n_epochs=100,
    save_path=training_dir,
    model_name="drosophila",
)

2026-02-04 14:10:45,500 [INFO] WRITING LOG OUTPUT TO C:\Users\6331823\.cellpose\run.log
2026-02-04 14:10:45,500 [INFO]
cellpose version: 	4.0.7
platform:       	win32
python version: 	3.11.0
torch version:  	2.7.1+cu128
2026-02-04 14:10:45,517 [INFO] not all flows are present, running flow generation for all images
2026-02-04 14:10:45,703 [INFO] 7 / 7 images in C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1\model folder have labels
2026-02-04 14:10:45,858 [INFO] ** TORCH CUDA version installed and working. **
2026-02-04 14:10:45,858 [INFO] >>>> using GPU (CUDA)
2026-02-04 14:10:46,789 [INFO] >>>> loading model C:\Users\6331823\.cellpose\models\cpsam
2026-02-04 14:10:47,451 [INFO] computing flows for labels

100%|██████████| 7/7 [00:00<00:00, 16.73it/s]

2026-02-04 14:10:47,870 [INFO] >>> computing diameters

100%|██████████| 7/7 [00:00<00:00, 638.53it/s]

2026-02-04 14:10:47,883 [INFO] >>> normalizing {'lowhigh': None, 'percentile': None, 'normalize': True, 'norm3D': True, 'sharpen_radius': 0, 'smooth_radius': 0, 'tile_norm_blocksize': 0, 'tile_norm_smooth3D': 1, 'invert': False}
2026-02-04 14:10:47,971 [INFO] >>> n_epochs=100, n_train=7, n_test=None
2026-02-04 14:10:47,972 [INFO] >>> AdamW, learning_rate=0.00001, weight_decay=0.10000
2026-02-04 14:10:47,973 [INFO] >>> saving model to C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1\model\models\drosophila

2026-02-04 14:10:49,452 [INFO] 0, train_loss=0.2040, test_loss=0.0000, LR=0.000000, time 1.48s
2026-02-04 14:10:53,518 [INFO] 5, train_loss=0.1796, test_loss=0.0000, LR=0.000006, time 5.54s
2026-02-04 14:10:57,639 [INFO] 10, train_loss=0.2010, test_loss=0.0000, LR=0.000010, time 9.67s
2026-02-04 14:11:05,520 [INFO] 20, train_loss=0.1567, test_loss=0.0000, LR=0.000010, time 17.55s
2026-02-04 14:11:13,450 [INFO] 30, train_loss=0.1453, test_loss=0.0000, LR=0.000010, time 25.48s
2026-02-04 14:11:21,401 [INFO] 40, train_loss=0.1636, test_loss=0.0000, LR=0.000010, time 33.43s
2026-02-04 14:11:29,285 [INFO] 50, train_loss=0.1535, test_loss=0.0000, LR=0.000005, time 41.31s
2026-02-04 14:11:37,234 [INFO] 60, train_loss=0.1278, test_loss=0.0000, LR=0.000001, time 49.26s
2026-02-04 14:11:45,253 [INFO] 70, train_loss=0.1485, test_loss=0.0000, LR=0.000000, time 57.28s
2026-02-04 14:11:53,143 [INFO] 80, train_loss=0.1829, test_loss=0.0000, LR=0.000000, time 65.17s
2026-02-04 14:12:01,071 [INFO] 90, train_loss=0.1656, test_loss=0.0000, LR=0.000000, time 73.10s
2026-02-04 14:12:08,204 [INFO] saving network parameters to C:\Users\6331823\Downloads\NIS3D\NIS3D\NIS3D\Drosophila_1\model\models\drosophila